oVirt/ovirt-engine

ovirt-engine.spec.in

Reverting commit 47290a80a78af0ce79daac932ac442fcfdc168d2 because it
broke both github and COPR builds

Revert: packaging: spec: require jaxb-api

---

.github/CODEOWNERS

Add codeowners for paths owned by the storage team
Signed-off-by: Benny Zlotnik <bzlotnik@redhat.com>

add storage codeowenrs

---

.github/CODEOWNERS

Looking at #53, there are too many owners.
The file:
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/backup/CreateScratchDisksCommand.java
Does not match:
backend/manager/modules/*/org/ovirt/engine/core/bll/storage/
So we get the default (*) owners.
Add "**" to match the missing "main/java/org", based on other patterns
in this file.
Signed-off-by: Nir Soffer <nsoffer@redhat.com>

github: Fix code owners patterns

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/backup/CreateScratchDisksCommand.java

To make the follow-up commit more focused on a specific change
extracting a few small fixes into a separate patch:
- Rename "addDisk()" method into "createScratchDisk()" in order to
reflect what the method really does and improve readability.
- Improving local variable's name.
- Updating a comment.
Signed-off-by: Pavel Bar <pbar@redhat.com>
Bug-Url: https://bugzilla.redhat.com/1913389

core: code refactoring in 'CreateScratchDisksCommand' class

---

.github/CODEOWNERS

Most of the work on ovirt-engine is not in my area of competence,
dropping myself as default codeowner.
I'm already listed as codeowner in the specific area which requires my
attention.
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

Dropping myself from default codeowners

---

frontend/webadmin/modules/frontend/src/main/resources/org/ovirt/engine/ui/frontend/server/dashboard/dao/ClusterDwhDAO.properties
frontend/webadmin/modules/frontend/src/main/resources/org/ovirt/engine/ui/frontend/server/dashboard/dao/HostDwhDAO.properties
frontend/webadmin/modules/frontend/src/main/resources/org/ovirt/engine/ui/frontend/server/dashboard/dao/StorageDomainDwhDAO.properties
frontend/webadmin/modules/frontend/src/main/resources/org/ovirt/engine/ui/frontend/server/dashboard/dao/VmDwhDAO.properties

Update Dashboard queries to use 4_5 DWH views.
This change should only be implemented in version 4.5
Bug-Url: https://bugzilla.redhat.com/2052503
Signed-off-by: Aviv Litman <alitman@redhat.com>

webadmin: update Dashboard queries to use 4_5 DWH views

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/MoveOrCopyDiskCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/storage/MultipleStorageDomainsValidator.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/disk/MoveOrCopyDiskCommandTest.java

The current validation, allDomainsHaveSpaceForDisksWithSnapshots, does not check for space on the target domain.
This PR introduces a new validation allTargetDomainsHaveSpaceForDisks method that validates the space on the target domain.
Bug: https://bugzilla.redhat.com/1913429

core: fix space validation for MoveOrCopyDiskCommand

---

packaging/services/ovirt-engine/ovirt-engine.conf.in
packaging/services/ovirt-engine/ovirt-engine.xml.in

- Add option to enable/disable sending server.log to remote syslog
- Do not pass log record timestamp to remote syslog
Bug-Url: https://bugzilla.redhat.com/2050218

Improve syslog handler options

---

.github/workflows/build.yml

Fix branch names for ovirt-engine-4.4 builds

---

packaging/services/ovirt-engine/ovirt-engine.conf.in
packaging/services/ovirt-engine/ovirt-engine.xml.in

Backport of #59 and #72 to ovirt-engine-4.4 branch
- Fix engine logs via syslog
- Add option to enable/disable sending server.log to remote syslog
- Do not pass log record timestamp to remote syslog
Bug-Url: https://bugzilla.redhat.com/2050218

Backport of #59 and #72

---

backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VDS.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VdsCpuUnit.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VdsDynamic.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/VdsDaoImpl.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/VdsDynamicDaoImpl.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VdsManager.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VdsBrokerObjectsBuilder.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VdsProperties.java
backend/manager/modules/vdsbroker/src/test/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VdsBrokerObjectsBuilderTest.java
frontend/webadmin/modules/gwt-common/src/main/resources/org/ovirt/engine/core/Common.gwt.xml
packaging/dbscripts/create_views.sql
packaging/dbscripts/upgrade/04_05_0160_add_cpu_topology_to_vds_dynamic.sql
packaging/dbscripts/vds_sp.sql

Parse cpu topology received from VDSM
and save it into vds_dynamic
This patch also retrieve the new vdsmToCpusAffinity, which let us know
on which pCPUs the VDSM is running on.
feature page: https://github.com/oVirt/ovirt-site/pull/2669
Change-Id: Ib77d4961eaf4e48e063d3448306d8570abb56972
Bug-Url: https://bugzilla.redhat.com/1782077
Signed-off-by: Saif Abu Saleh <sabusale@redhat.com>

core: dedicated cpus - parse and save cpu topology

---

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/MainSectionView.java

In the main navigation list, support opening secondary navigation menu
by pressing "enter" key. This unblocks keyboard only navigation.
Bug-Url: https://bugzilla.redhat.com/2001904

webadmin: open navigation sub-menu on "enter" key

---

backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/NetworkInSyncWithVdsNetworkInterface.java
backend/manager/modules/utils/src/test/java/org/ovirt/engine/core/utils/NetworkInSyncWithVdsNetworkInterfaceTest.java

When a user configures a 0.0.0.0 gateway, vdsm reports it back as an
empty string which engine then converts into null. Comparing null to the
configured 0.0.0.0 results in reporting the attachment as out of sync
when actually null signifies 'no gateway' as is signified by 0.0.0.0
Therefore, align the comparison predicate with this corner case.
Change-Id: I48d6039dd1044ce5997f8bb152785ab0d78b4e54
Bug-Url: https://bugzilla.redhat.com/1993016

core: no gateway 0.0.0.0 should be in sync

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AddVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/CloneVmCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/CloneVmParameters.java

(Original fix: https://gerrit.ovirt.org/c/ovirt-engine/+/118343/ and https://gerrit.ovirt.org/c/ovirt-engine/+/118169).
When cloning a VM with an MBS disk, the method getSourceDisks() is being used for getting and filtering the target disks for cloning.
Currently, the MBS disks are filtered by their pluggability.
During the cloning process, a VM snapshot is being created, and its disks are marked as un-plugged and not active.
Therefore, the MBS disks are filtered out from the images' list.
When trying to remove the snapshot and retrieve the disks, there's an NPE, and the clone operation fails.
This patch skips the snapshots' creation (and removal) in case of a non-running VM with MBS disks.
Another issue is that the VM is being cloned without the MBS disks.
This patch deals with that …

core: skiping snapshots for VMs with MBS disks and attaching MBS disks while cloning a VM

---

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/gin/PresenterModule.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/presenter/tab/host/HostDeviceActionPanelPresenterWidget.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/presenter/tab/host/SubTabHostDevicePresenter.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/tab/host/SubTabHostDeviceView.java

In order for the ui-extensions to be able to add the action button to the host devices tab, the action panel needs to be present.
This patch creates and injects the action panel presenter to the host devices tab.

webadmin: Add an action panel to host device tab

---

i18n/zanata.xml

To support distinct translations between ovirt 4.4 and ovirt 4.5,
point zanata to the `ovirt-4.5` version [1] of the ovirt-engine
project in zanata.
[1] - https://zanata.ovirt.org/iteration/view/ovirt-engine/ovirt-4.5

i18n: bump zanata project version to ovirt-4.5

---

.github/workflows/ost.yaml

Enabling /ost trigger to run system tests
Signed-off-by: Artur Socha <asocha@redhat.com>

automation: enable ost trigger

---

ovirt-engine.spec.in
packaging/conf/fapolicyd-55-allow-ovirt-jboss.rules.in
packaging/setup/ovirt_engine_setup/engine_common/constants.py
packaging/setup/plugins/ovirt-engine-common/ovirt-engine-common/system/__init__.py
packaging/setup/plugins/ovirt-engine-common/ovirt-engine-common/system/fapolicyd.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/config/__init__.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/config/jboss_fapolicyd.py

In order to be able to run Ovirt Engine on host with enabled fapolicyd
rules the custom Wildfly/EAP runtime temporary dir had to allowed. It
was achieved using newly added fapolicyd support for rules.d [1]
This change is also required for DISA STIG
[1] https://github.com/linux-application-whitelisting/fapolicyd/issues/117
Signed-off-by: Artur Socha <asocha@redhat.com>

packaging: fapolicyd allow Wildfly/EAP runtime tmp

---

.github/CODEOWNERS

Remove myself (almusil) from the default maintainers,
while still being mentioned on network related code.

CODEOWNERS: Remove almusil from default

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AddVmTemplateFromSnapshotCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/CreateAllTemplateDisksFromSnapshotCommand.java

Currently, when creating a template from a snapshot which has MBS disks,
the operation is being completed successfully since the MBS disks are
being omitted from the resulted template.
As that operation isn't being currently supported for MBS disks, it should be blocked.
This patch avoids filtering out the MBS disks and leads to the deserved
outcome of blocking the operation.
Bug-Url: https://bugzilla.redhat.com/2004350

Block creation of a template from a snapshot with MBS disk(s)

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/backup/CreateScratchDisksCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/backup/RemoveScratchDisksCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/backup/StartVmBackupCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/VmBackupParameters.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VmBackupPhase.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/vdscommands/ScratchDiskInfo.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/vdscommands/VmBackupVDSParameters.java
backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/VmBackupMapper.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VmBackupConfigVDSCommandBase.java

In order to minimize scratch disk initial size VDSM requires a few additional parameters
that previously were not passed to it at the scratch disk map.
This patch adds the required parameters to make the initial disk allocation more efficient.
This PR consists of 2 gerrit patches that were pretty much code-reviewed in gerrit with all comments resolved:
1) Some refactoring to pass full scratch disk info in 'VmBackupVDSParameters'.
https://gerrit.ovirt.org/c/ovirt-engine/+/118402
2) Using the scratch disk info to generate the required "scratch_disk" configuration object for VDSM:
https://gerrit.ovirt.org/c/ovirt-engine/+/118305
Another 2 commits were added as the 1st and 2nd ones that contain a code refactoring to unite 'PREPARING_SCRATCH_DISK' & 'STARTING' phases into a single one. …

Add parameters to minimize scratch disk initial size

---

.automation/build-srpm.sh
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/config/jboss_fapolicyd.py

Replace 'make generated-files' with 'make validations', so that we run
code validations per build.
'validations' already depends on 'generated-files' so we do not need
both.
Change-Id: I227bdd71af7dcf9a692c025c77525cb57aec2e0d

automation: Run validations

---

packaging/setup/ovirt_engine_setup/engine_common/constants.py
packaging/setup/ovirt_engine_setup/util.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine-common/apache/ssl.py

In EL8, SSLProtocol is best handled by crypto-policies - no need to
hard-code any specific values in our own code.
In new setups - where SSLProtocol is already not set by default in
ssl.conf, relying on crypto-policies - just do nothing.
In upgrades from previous setups, where we did set SSLProtocol, comment
out the SSLProtocol line.
I wanted to keep using editConfigContent for this, relying on its
docstring saying that params set to (python) None are removed. But this
does not work - was never used, so not noticed so far.
Trying to fix this using the existing code was hard, and the code was
too complex and hard to understand in my opinion, so I mostly rewrote
it. I hope the new code is easier to understand and maintain.
Bug-Url: https://bugzilla.redhat.com/1999698
Change-Id: …

packaging: setup: httpd/ssl: Clear SSLProtocol

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelper.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VdsManager.java

When using older hosts, the cpu_topology is not reported from the host
caps. This caused a NullPointerException when streaming over the list,
as the list is a null and not an empty list.
On the VdsCpuUnitPinningHelper, when using manual pinning and by the
CpuPolicyUnit a caution about empty CPU topology needed.
This patch will initiate the VdsManager cpuTopology, to have an empty
list instead of null. Also, when entering some flows in the helper if
the cpuTopology is empty we should return immediately.
Change-Id: I6801dbbf4c63f96061a4c16dd001fb7260c717a1
Bug-Url: https://bugzilla.redhat.com/1782077

core: fix NPE on cpuTopology

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelper.java

This patch will let the scheduler to deal with mismatch of the host
topology with the online CPUs it has.
It's partially done to not break non-Dedicated flows.
Change-Id: Ib91401c88e0e1e87f3ba1076c8e076f1822549d6

core: consider offline cpus

---

backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/VmMapper.java

The VM mapper was not creating DynamicCpu instance for dedicated CPUs which resulted in NPE.
This patch changes the order of filling the model - at first, if the cpu pinning policy is dynamic, the DynamicCpu is created. Then, if the dynamic pinning is numa resize and pin, the dynamic cpu topology is set.

restapi: fix vm mapper

---

packaging/dbscripts/upgrade/pre_upgrade/0000_config.sql

The time when event are created to warn of upcoming certificate
expiration were extended:
1. If a certificate is going to expire in the upcoming 120 days, then
WARNING event is raised in the audit log
2. If a certificate is going to expired in the upcoming 30 days, then
ALERT event is raised in the audit log
Bug-Url: https://bugzilla.redhat.com/2056126

core: Extend time to warn of upcoming certificate expiration

---

backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VdsManager.java

In VdsManager, we should consider scenario where vds affinity is null or String not parsable to Integer.

engine: handle case where cpu affinity is null

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommand.java

Currently when a transfer will fail stopImageTransferSession as part of
handleFinalizingSuccess it will finish successfully, leaving garbage
behind and the image will remain locked.
This patch is a partial revert of c54d500.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2057445

core: fix retry for transfer image stopImageTransferSession failure

---

frontend/webadmin/modules/frontend/src/main/java/org/ovirt/engine/ui/frontend/server/dashboard/Dashboard.java
frontend/webadmin/modules/frontend/src/main/java/org/ovirt/engine/ui/frontend/server/dashboard/DashboardDataServlet.java

To be able to display a link to the Montioring Portal on the
dashboard on `ovirt-engine-ui-extensions`, the link needs to be
passed along with the rest of the dashboard info.  If grafana is
not configured on the engine, null is returned.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1991482

Send grafana link with dashboard data

---

backend/manager/modules/uutils/src/main/java/org/ovirt/engine/core/uutils/ssh/OpenSSHUtils.java
ovirt-engine.spec.in
pom.xml

Recently released apache-sshd >= 2.7.0 is incompatible with our
implementation in engine. This patch ensures apache-sshd won't get
automatically upgraded with 'dnf upgrade'

packaging: bump apache-sshd to 2.8.x

---

frontend/webadmin/modules/frontend/src/main/java/org/ovirt/engine/ui/frontend/server/gwt/GwtDynamicHostPageServlet.java
frontend/webadmin/modules/frontend/src/main/resources/META-INF/resources/GwtHostPage.jsp
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/CommonApplicationConstants.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/CommonApplicationMessages.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/place/ApplicationPlaceManager.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/section/main/presenter/OptionsPopupPresenterWidget.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/view/popup/OptionsPopupView.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/view/popup/OptionsPopupView.ui.xml
frontend/webadmin/modules/gwt-common/src/main/resources/org/ovirt/engine/ui/common/CommonApplicationConstants.properties
frontend/webadmin/modules/gwt-common/src/main/resources/org/ovirt/engine/ui/common/CommonApplicationMessages.properties
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/options/CustomHomePageField.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/options/EditOptionsModel.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/options/OptionsModel.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/options/UseCustomHomePageField.java
frontend/webadmin/modules/uicompat/src/main/java/org/ovirt/engine/ui/uicompat/UIConstants.java
frontend/webadmin/modules/uicompat/src/main/resources/org/ovirt/engine/ui/uicompat/UIConstants.properties

Home page setting allows to customize the welcome page displayed when
UI is accessed via base URL (without the fragment part).
Key points:
1. the home page is described by a fragment part of the URL and
contains encoded information about the screen to be displayed
2. two new properties were added for this feature:
a) "webAdmin.useCustomHomePage" - boolean (default: false)
b) "webAdmin.customHomePage" - string - the fragment to be used
3. the fallback for incorrect or obsolete home page is the default page
(the dashboard if ui-extensions are used). The flow is the same as
if an incorrect fragment was entered manually.

webadmin: add home page to Account Settings

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AnsiblePackOvaCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/GetFromOvaQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ExportOvaCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ExtractOvaCommand.java
packaging/ansible-runner-service-project/project/roles/ovirt-ova-export-post-pack/tasks/main.yml
packaging/ansible-runner-service-project/project/roles/ovirt-ova-export-pre-pack/tasks/main.yml
packaging/ansible-runner-service-project/project/roles/ovirt-ova-extract/tasks/main.yml
packaging/ansible-runner-service-project/project/roles/ovirt-ova-pack/tasks/main.yml
packaging/ansible-runner-service-project/project/roles/ovirt-ova-query/tasks/main.yml

OVA is invoking tasks that are running for a long time
as script or command, this can result in ssh closing connection
before the task has a chance to finish. Use async on those
commands which makes ansible to poll every 15 seconds to check
if the command succeeded.
Bug-Url: https://bugzilla.redhat.com/2056052

ansible: Add async with timeout for OVA related tasks

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/network/NetworkConfigurator.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/network/NetworkConfiguratorTest.java

The network configurator was comparing only string
representation of IP addresses which could lead to
trying to setup management network even when there was
already one on the host.
The problem is most obvious for the IPv6, the InetAddress
returns expanded form of address e.g. "fbc::10" becomes
"fbc:0:0:0:0:0:0:10" which compared to the original
unexpanded form fails.
To prevent this use IPAddressPredicate to compare the values,
as the predicate is capable of comparing expanded and
unexpanded form.
Bug-Url: https://bugzilla.redhat.com/2061904

core: Fix wrong IP comparison in NetworkConfigurator

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ConvertDiskCommand.java

If no hosts are found ConvertDiskCommand will exit, having execution status failed, but since it is an async command, it will execute endSuccessfully because no child commands failed.
By setting CommandStatus to FAILED, this patch will force the command to go endWithFailure.
Bug: https://bugzilla.redhat.com/2063802

core: mark command as failed if no hosts are found

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/policyunits/CpuPinningPolicyUnit.java

When running a Resize and Pin NUMA VM, the validation thinks the CPU
pinning already set. But that is incorrect for this flow. It is set only
in the last phase on running the VM. The validation results in an NPE in
such case.
Change-Id: I83cf61d8b5f82187222ca0f2ee5085dde97452c6

core: fix resize and pin scheduling

---

ovirt-engine.spec.in

Add dependency on scap-security-guide that contains
all fixes for RHV.

spec: Add dependency on scap-security-guide

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmPoolResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmPoolsResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmsResource.java

The 'seal' parameter is added to VM creation and to VM Pool creation and
update, when VMs may be created for the pool.
Change-Id: Ibc053f1e581142d81c3e60cfe251da5187dfa8f4
Bug-Url: https://bugzilla.redhat.com/2054681

restapi: Add 'seal' parameter for created VMs

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmPoolResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmPoolsResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmsResource.java

When specifying the 'seal' argument on the API without a value, it will be considered as TRUE

Default empty 'seal' argument to true

---

packaging/ansible-runner-service-project/project/roles/ovirt-host-setup-vnc-sasl/README.md
packaging/ansible-runner-service-project/project/roles/ovirt-host-setup-vnc-sasl/tasks/main.yml

currently Passwd use sha-1 which is deprecated, we should move to
sha-256.

ovirt-host-setup-vnc-sasl: Update to scram-sha-256

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/json/CustomObjectMapperFactory.java

This patch fixes an issue introduced during the migration from codehaus
jackson into fasterxml jackson that resulted in serialization of nulls.
Now such fields are skipped.
Bug-Url: https://bugzilla.redhat.com/2032917

restapi: do not serialized nullable fields

---

packaging/setup/dbutils/fkvalidator_sp.sql

This patch fixes an issue with fk validator.
The root cause was the fact that this store procedure incorrectly parsed
foreign key column from the constraint definition. Table column was
always chosen whereas there should a referenced (foreign) column
selected.
In example:
Let's take one fk constraint body:
FOREIGN KEY (group_id) REFERENCES ad_groups(id)
Before that patch 'fk_col' would be always resolved to 'group_id'. After
applying the patch it would be 'id'  (from 'ad_groups' table)
Now the expected fk check sql should take a form of:
select (group_id) from public.tags_user_group_map where (
group_id)IS NOT NULL
and (id) not in (select id from public.ad_groups)
In case non empty results fkvalidator would raise an error (as expected
for such integrity check)

[db] fkvalidator fix

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/users/UserEventNotifierListModel.java

This patch fixes the displayed email for event notification when
selecting a user details in Administration->Users and on the "Event
Notifier" tab clicking on the "Manage Events" button.
In the opened popup form the field "Mail Recipient" should contain the
mail for notification sending, by default this is the mail that the user
has in the database "users" table but can be set to any other email
address.
The "Mail Recipient" field should display any other mail set for
subscription and only if it is not set then the value from the "users"
table should be used.
The bug was that the code used the email from the "users" table without
checking if it was overridden for event notifications.
Signed-off-by: Eli Mesika <emasika@redhat.com>
Bug-Url: https://bugzilla.redhat.com/1994144

fix manage events form email display

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ConvertDiskCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/CreateVolumeContainerCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/ConvertDiskCommandParameters.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendDiskResource.java

Support sending backup mode when converting disks. This will allow converting a disk to cow-preallocated in one request.

core: support backup in convert disk

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AddVmTemplateCommand.java

We've noticed a race in our **beloved testing framework** (OST) between AddVmTemplate and UpdateVmVersion
This should prevent it by making sure AddVmTemplate releases its locks before calling UpdateVmVersion
In more details, we've noticed the following race:
1. 2022-03-15 11:30:21,740Z INFO  [org.ovirt.engine.core.bll.AddVmTemplateCommand] ...
Lock Acquired to object 'EngineLock:{exclusiveLocks='[f05484e6-9fb4-446d-904b-56932120c747=TEMPLATE]',
sharedLocks='[58dd14eb-ba04-4687-98e1-f5aac18df59b=TEMPLATE, 59f5dd98-212f-4324-9081-44c198c6653a=VM]'}'
2. 2022-03-15 11:30:21,756Z INFO  [org.ovirt.engine.core.bll.AddVmTemplateCommand] ...
Running command: AddVmTemplateCommand
3. 2022-03-15 11:30:24,400Z WARN  [org.ovirt.engine.core.bll.UpdateVmVersionCommand] ...
Validation of action …

Eliminate a race between AddVmTemplate and UpdateVmVersion

---

backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelperTest.java

This patch disables a broken unit test in the dedicated feature.
It breaks CI and builds.
Change-Id: I3f0bf90418f03dbd36e1991dbe1a6278911b21b8

core: disable broken test in dedicated

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendHostCpuUnitsResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendHostResource.java

In order to let the unit tests pass, we need to stub the
HostCpuUnitsResource.
Change-Id: I130ae6c14d1d51cf58f3d835639628c5a9db56a8

restapi: stub HostCpuUnitsResource

---

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/tab/virtualMachine/VmHostDeviceModelTable.java

The fix applies to rows in Virtual Machines -> {vm} -> Host Devices
table that have the IOMMU placeholder flag enabled.
Before, such rows were repeatedly switching between "enabled" and
"disabled" CSS styles. The problem was fixed by using an extension
point dedicated to row CSS customization.

webadmin: fix displaying IOMMU placeholder rows

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/ClearNonResponsiveVdsVmsCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/ProcessDownVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RestartVdsVmsOperation.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommandBase.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/ProcessDownVmParameters.java

The ProcessDownVmCommand fails with NPE if the host id is null. This patch makes it mandatory for the caller to provide the host id and fails with IllegalArgumentException if the provided host id is null.

engine: make host id mandatory for ProcessDownVmParameters

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/SchedulingManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/pending/PendingCpuPinning.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/policyunits/CpuPinningPolicyUnit.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelper.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelperTest.java

This patch will introduce new logic to the way dedicated CPUs are
selected to be used for a VM. Now, we consider the user defined
topology.
Change-Id: I30a467d7a6861eb477598c3ec42b20183caa2359

core: consider user defined topology

---

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/gin/PresenterModule.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/presenter/tab/virtualMachine/SubTabVirtualMachineVmDevicePresenter.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/presenter/tab/virtualMachine/VmDeviceActionPanelPresenterWidget.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/tab/virtualMachine/SubTabVirtualMachineVmDevicesView.java

In order for the ui-extensions to be able to add the action button to the vm devices tab, the action panel needs to be created.
This patch creates and injects the action panel presenter to the vm devices tab.

Add an action panel to vm devices tab

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VdsEventListener.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/hostdev/HostDeviceManager.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/IVdsEventListener.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/monitoring/VmsMonitoring.java

ProcessDownVm removes unmanaged devices of stateless VMs and VMs that were started in run-once mode. Therefore, we now check whether VMs are set with host devices, in order to determine whether the host should be refreshed, before calling ProcessDownVm.

Fix refreshing of mdev devices when VMs with run-once configuration stop

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmHandler.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/SchedulingManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelper.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelperTest.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VdsCpuUnit.java

Since we introduced `dedicated` policy, we need to allocate the physical
resources even for other policies such: `manual` and `resize and pin
NUMA`. Until now the CPU topology and CPU pinning for `resize and pin
NUMA` happened after host selection by the scheduler. But in that phase
we allocate the physical resources, which result us in NPE and
potential to wrong data for the host resources.
Now, the CPU settings such as topology and CPU pinning will be generated
after host selection, when allocating the physical CPUs.
Change-Id: Iff425646825cd258a9c35c88f36cd4b66618eac5

core: move resize and pin CPUs settings

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/GetDiskIdBySnapshotIdQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommand.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommandTest.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/queries/QueryType.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendImageTransfersResource.java

Currently when downloading snapshots the disk_id would remain empty.
This may cause issues if this field is accessed, which happens when
moving a host to maintenance and will lead to NPEs.
Since snapshots in the system are always part of a disk, this patch sets
the snapshot's disk_id when transfer request is made.
Bug-Url: https://bugzilla.redhat.com/2043984
Signed-off-by: Benny Zlotnik <bzlotnik@redhat.com>

core: set disk_id when downloading snapshots

---

packaging/ansible-runner-service-project/project/ovirt-host-reconfigure-ovn.yml
packaging/ansible-runner-service-project/project/ovirt_host_upgrade_vars.yml

The upgrade lefts chassis in strange state causes
ovn-controller to lose tunnel connection. To fix that
remove the old chassis after upgrade, which gives
ovn-controller chance to introduce the host again
with proper configuration.
Bug-Url: https://bugzilla.redhat.com/1940824

ansible: Sync OVN SB DB chassis after upgrade

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AddVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/UpdateVmCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/MDevTypesUtils.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/customprop/CustomPropertiesUtils.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfReader.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfWriter.java

We dropped the custom property mdev_type from the predefined properties 
in favor of (fake) VM devices. However, this breaks backward compatibility
with clients that specify the vGPU settings using this custom property.
Therefore PR changes add-VM and update-VM to respect the mdev_type 
custom property when specified. Note that the custom property was already 
converted to VM devices when reading an OVF and that covered most of the 
cases, like snapshots that were taken while mdev_type existed - that
code is now being reused in the aforementioned flows.

Respect deprecated custom property mdev_type on add/update VM

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmHandler.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/SchedulingManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/policyunits/CpuPinningPolicyUnit.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/policyunits/HighPerformanceCpuPolicyUnit.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/utils/NumaPinningHelper.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelper.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/InClusterUpgradeValidator.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/policyunits/CpuAndNumaPinningWeightPolicyUnitTest.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/validator/InClusterUpgradeValidatorTest.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VM.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VdsCpuUnit.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/CpuPinningHelper.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/VmCpuCountHelper.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendHostCpuUnitsResource.java
backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/VmMapper.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VdsManager.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/builder/vminfo/LibvirtVmXmlBuilder.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/builder/vminfo/VmInfoBuildUtils.java

When creating a VM without CPU pinning but with NUMA pinning the engine
generated CPU pinning according to the NUMA pinning of the VM. It was
made to ensure the virtual CPUs are using the right physical CPU in the
desired NUMA. The CPU pinning was not saved to the DB, it was written to
the VM domain XML.
Since the new CPU pinning policies, VDSM requires a policy that is not
`none` to save the CPU pinning of the VM when migrating it to a new
host. Also, for supporting `dedicated` policy, the engine needs to know
what the status of usage of each physical CPU.
Therefore, the generated CPU will happen on scheduling, right after the
host being selected and will be saved to the dynamic CPU.
Change-Id: I9a10e1e6b2e2933cd0f96a20192e9837944d79b7
Bug-Url: https://bugzilla.redhat.com/2065152 …

Handle numa pinning without cpu pinning

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/MigrateVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommandBase.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/StopVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/vdscommands/MigrateVDSCommandParameters.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/VmDynamicDao.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/VmDynamicDaoImpl.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/monitoring/VmAnalyzer.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/MigrateBrokerVDSCommand.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VdsProperties.java
packaging/dbscripts/vms_sp.sql

This patch lets dedicated VM to be migrated. It will keep to maintain
the cpuTopology for manual and dedicated pinnings. The `cpusets` sent to
the VM.Migrate verb in VDSM. Where VDSM modify the domxml of `cputune`
to the new pinning.
Change-Id: Ib31de1d26459a3712d0d113418f9fd848a411e3c
Bug-Url: https://bugzilla.redhat.com/1782077

Add migration support for dedicated policy

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferImageCommandCallback.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommandTest.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VDSDomainsData.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VdsBrokerObjectsBuilder.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VdsProperties.java

Improve the handling of some negative scenarios in TransferDiskImage:
* Failure during executeCommand() will lead to a stuck transfer, because polling will not continue and the command is not marked as failed
* Filter out hosts the have the target domains not reported as "valid: True", to avoid using hosts that might not be ready to service requests and failing
* Check if actually managed to initiate the transfer before continuing
* Set ImageTicketId before adding it in imageio to avoid looping trying to stop a transfer for a ticket that does not exist

Change handling of negative scenarios in TransferDiskImage

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommand.java

RAW disks being backed up in a backup that uses a checkpoint are considered incremental instead of full, if they have qcow overlay. Instead we need to consider the backup mode set for the disk
* Do not use the bitmap if the disk being transfer has the full backup mode
* Do not use dirty extents if the disk being transfer has the full backup mode
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2068104

core: fix treatment of disks with full backup mode

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommandBase.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmHandler.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/SchedulingManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/policyunits/CpuAndNumaPinningWeightPolicyUnit.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/policyunits/NumaPolicyUnit.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelperTest.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VM.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VdsCpuUnit.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VmDynamic.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/CpuPinningHelper.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/NumaPinningHelper.java
backend/manager/modules/common/src/test/java/org/ovirt/engine/core/common/utils/NumaPinningHelperTest.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/VmDynamicDaoImpl.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/ResourceManager.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VdsManager.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/builder/vminfo/LibvirtVmXmlBuilder.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/NumaSettingFactory.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VdsBrokerObjectsBuilder.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VdsProperties.java
backend/manager/modules/vdsbroker/src/test/java/org/ovirt/engine/core/vdsbroker/vdsbroker/NumaSettingFactoryTest.java
backend/manager/modules/vdsbroker/src/test/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VdsBrokerObjectsBuilderTest.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/ExistingVmModelBehavior.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/UnitVmModel.java
frontend/webadmin/modules/uicompat/src/main/java/org/ovirt/engine/ui/uicompat/UIConstants.java
frontend/webadmin/modules/uicompat/src/main/resources/org/ovirt/engine/ui/uicompat/UIConstants.properties
packaging/dbscripts/create_views.sql
packaging/dbscripts/upgrade/04_05_0240_add_current_numa_pinning_to_vm_dynamic.sql
packaging/dbscripts/vms_sp.sql

When using dedicated cpu policy together with numa, the numa pinning should be created when the vm starts and
cleared when the vm shuts down.

Add numa to dedicated

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmFromConfigurationCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmTemplateCommandBase.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmTemplateFromConfigurationCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/ovfstore/OvfUpdateProcessHelper.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/ImportValidator.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/storage/DiskImagesValidator.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/exportimport/ImportVmCommandTest.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/validator/storage/DiskImagesValidatorTest.java

Until now the VM shared disks were not part of the 'OVF STORE' configuration.
Adding them to be part of the 'OVF STORE' configuration.
That allows VMs to share disks, move to another environment (`Storage Domain` Detach & Attach) and after being imported still share the same disks without any additional configuration.
Previously those shared disks' configuration was "lost along the way".
Signed-off-by: Pavel Bar <pbar@redhat.com>
Bug-Url: https://bugzilla.redhat.com/1922977

Add VM shared disks to 'OVF STORE' configuration

---

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/widget/table/column/ClusterUpgradeStatusColumn.java

Given REST changes in [1] and [2], when a cluster is marked as upgrade in progress, show the progress value as a progress bar on the cluster grid.
[1] - https://github.com/oVirt/ovirt-engine-api-model/pull/32
[2] - https://github.com/oVirt/ovirt-engine/pull/170
Bug-Url: https://bugzilla.redhat.com/2040474
~~_Note: This PR is dependent on #170 so it currently includes those commits as well.  Only the last commit belongs to this PR.  I will rebase as needed and as merges happen._~~

webadmin: Cluster grid upgrade status column as progress bar

---

pom.xml

Remove whitespace which interferes with
sdk generation
Fix populating documentation
Add RPM build
Signed-off-by: Ori Liel <oliel@redhat.com>

bump model version to 4.5.7

---

backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfProperties.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfReader.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfWriter.java

We need to have not only for export-import but also for keeping it when next-run configuration is created and when restoring snapshots

Add console disconnect action delay to OVF

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/SchedulingManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelper.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelperTest.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/NumaPinningHelper.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/NumaUtils.java
backend/manager/modules/common/src/test/java/org/ovirt/engine/core/common/utils/NumaUtilsTest.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/NumaSettingFactory.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/builders/vm/NumaUnitToVmBaseBuilder.java

When we have virtual NUMA provided with a dedicated VM, we wish to pin
that virtual NUMA to a physical NUMA. But we have a memory constraint.
The future physical resources we are going to use needs to provide
enough memory in order to use it.
This needed to be considered when scheduling such VM and selecting the
physical resources to use.
For now the NUMA will use the tune `interleave`, that would let the
memory pages to be used from multiple physical NUMA nodes.
Change-Id: I9d3a79296391cd77f7d53cc75eb152383dba9137

Consider numa memory to dedicated scheduling

---

packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vdsm/tasks/configure.yml

currently, vdsm-mom service is blocked by one of the fapolciy rules,
adding an exception rule for the service.
Bug-Url: https://bugzilla.redhat.com/2015802

fapolicy: add allow rule for vdsm-mom

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/backup/HybridBackupCommand.java

Hybrid backup should only backup the disks selected for the backup (i.e.with --disk-uuid <id>).
This change uses the selected disks when creating the snapshot to ensure only the selected disks participate in the snapshot.
Bug-Url: https://bugzilla.redhat.com/2070184

core: only use selected disks for hybrid backup

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/network/RemoveNetworkParametersBuilder.java

The long name networks are represented on the host as onUUID.
When the network is unmanaged and the attachment is gone we need
to remove network based on it's vdsm name and not the name
that it had in engine. Use vdsmName for removal of unmanaged
interfaces instead of the engine name.

core: Fix removal of unmanaged network with long name

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/ExistingVmModelBehavior.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/NewVmModelBehavior.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/VmModelBehaviorBase.java
frontend/webadmin/modules/uicompat/src/main/java/org/ovirt/engine/ui/uicompat/UIConstants.java
frontend/webadmin/modules/uicompat/src/main/resources/org/ovirt/engine/ui/uicompat/UIConstants.properties

When the latest version of the template is selected in the new VM dialog, the VM has to remain stateless no matter what is set on the template. To ensure that (and to allow the selection of the latest statefull template), the field is automatically disabled and checked as Stateless.
When creating a VM, the clone provisioning is selected by default. That does not make much sense for the latest template because the purpose of the latest template version is to be able to apply template's latest changes to the vm. This patch changes the selected provisioning to thin if the latest template is selected.

Disable Stateless VM field

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/NewTemplateVmModelBehavior.java

When creating a new template, there was a race that caused the number of cpus to reset to the minimal
number of cpus required for the cluster.

webadmin: Fix race when creating a new template

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ConvertDiskCommand.java

When converting a disk on block storage to qcow2, we might not have enough space for the qcow metadata on the created volume if it is converted from RAW format.
* Measure the required size before creating the skeleton volume, and if the required size is smaller than required, the returned size will be used
* Set the size returned by getVolumeInfo to fix the size of the new volume in case it changed after conversion
Bug-Url: https://bugzilla.redhat.com/2069670

core: measure volume before starting conversion

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/UpdateVmVersionCommand.java

If the vm and the template are not on the same cluster, adding of the newly created vm fails because of the validation
of the cpu profile (it requires the cpu profile to be from the vm's cluster, but it is actually copied from the template on a different cluster).
This patch keeps the original cpuProfile in vm's configuration if the template is on a different cluster.

engine: keep original cpuProfile in UpdateVmVersionCommand

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmHandler.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/SchedulingManager.java

When initiating a dedicated VM the NUMA pinning is automatically generated by the engine, based on the physical CPU taken. This patch will take into consideration the memory such VM needs and set it to the NUMA pending resources.

Consider NUMA pending resources for a dedicated VM

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/UpdateVmVersionCommand.java

When updating a version of a VM, there might be some asynchronous operations running which could cause the endCommand() to be called with null getVm() and null getVmTemplate(). We should rely solely on the parameters at this point.

engine: move setting of cpu profile to execute

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ConvertDiskCommand.java

Currently child commands like DestroyImage and CreateVolumeContainer will unlock the exclusive lock acquired by ConvertDisk as the lock is implicitly passed down to them.
This PR changes the execution context to one that does pass the locks down to prevent the premature unlock.
Bug-Url: https://bugzilla.redhat.com/2069670
Depends on: https://github.com/oVirt/ovirt-engine/pull/203

core: fix locks in ConvertDiskCommand

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerHttpClient.java

If playbook artifacts directory is not yet populated (it may happen
when we use async mode to run playbooks), return 0 as total number
of events to prevent NPE.
Bug-Url: https://bugzilla.redhat.com/2052690

Fix NPE in AnsibleRunnerHttpClient.getTotalEvents

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleCommandConfig.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleExecutor.java

Continuation of https://github.com/oVirt/ovirt-engine/pull/214
Adding the project-dir when executing ansible-playbook with
ansible-runner. This allows us to have seperated runs of the
playbooks without the copying whole project directory.
Code cleanup in AnsibleCommandConfig.

Use ansible-runner project-dir and code cleanup

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleCommandConfig.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleExecutor.java

Continuation of https://github.com/oVirt/ovirt-engine/pull/214
Adding the project-dir when executing ansible-playbook with
ansible-runner. This allows us to have separated runs of the
playbooks without the copying whole project directory.
Code cleanup in AnsibleCommandConfig.

Use ansible-runner project-dir and code cleanup v2

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerHttpClient.java

The ansible-runner was getting full list of artifacts even with partial
json files, which should be ignored. Because of that the ansible-runner
wrote multiple times to the log the same log.

Ansible-runner: fix getting the list of all files

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/InitVdsOnUpCommand.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VdsManager.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/monitoring/HostMonitoring.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/hosts/HostGeneralModel.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/ApplicationConstants.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/tab/host/HostGeneralSubTabView.java
frontend/webadmin/modules/webadmin/src/main/resources/org/ovirt/engine/ui/webadmin/ApplicationConstants.properties

When we have a new cluster, the FIPS mode is defined by the first host
being added to that cluster. By default the value of it when unavailable
from the host is `false`. In case of new host deployment to that cluster
and reboot, we may not get the capabilities as expected and even when
the host is with FIPS set, it will still wrongly set the cluster with
`false`, making the host non-operational until the cluster is edited by
the user to be FIPS `true`.
The placement the engine handles the FIPS is moved to a place we can be
certain we already get the capabilities from the host. Therefore, we
will always set it with the right value of the first host in that new
cluster.
Change-Id: I3c21028e3bd0f882340afc13ab05911fb92ec90c
Bug-Url: https://bugzilla.redhat.com/2065543
Signed-off-by: Liran …

Fix racing cluster FIPS settings

---

packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vdsm/tasks/configure.yml

adding exclusion rule to fapolicy for vdsm-mom was a condition by the os
distro. since rhv host doesn't have fapolicy it caused a failure.
add the exclusion rule to fapolicy only when fapolicy service is
running.

fix: add fapolicy exclusion rule

---

packaging/services/ovirt-engine-notifier/ovirt-engine-notifier.conf.in
packaging/services/ovirt-engine/ovirt-engine.conf.in

Ensure that the following properties are not logged in plain text:
- KEYCLOAK_DB_PASSWORD 
- EXTERNAL_OIDC_HTTPS_PKI_TRUST_STORE_PASSWORD,
- EXTERNAL_OIDC_CLIENT_SECRET 
Bug-Url: https://bugzilla.redhat.com/2021497

engine: hide openidc related sensitive keys

---

packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-hosted-engine/tasks/deploy.yml

A recent change somewhere, not sure, creates the file
/etc/ovirt-hosted-engine/hosted-engine.conf with root:root, 0400.
ovirt-ha-broker fails to read it like this.
So: Fix, by setting explicitly the owner/group/permissions we want for
this file.
Change-Id: I4525273a1146854d808ea2ef8bc31b1741d61004

ansible: Set explicit owner/permissions for hosted_engine_conf

---

ovirt-engine.spec.in

Upgrade collectd requirements to >= 5.12.0-7
Bug-Url: https://bugzilla.redhat.com/1868372
Signed-off-by: Aviv Litman <alitman@redhat.com>

collectd-virt plugin doesn't work with latest libvirt

---

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/widget/table/column/ClusterAdditionalStatusColumn.java

When rendering the ClusterAdditionalStatusColumn, the cluster.getHostNamesOutOfSync() might be null if the
async backend query failed. As a result, we get the NP exception because we check only if the string is empty, not if it is null. This patch adds a null check to ClusterAdditionalStatusColumn::getEntityValue.

Null check in ClusterAdditionalStatusColumn

---

packaging/services/ovirt-engine/ovirt-engine.xml.in

This patch add a file logger dedicated for keycloak runtime messages.
Before that patch all mentioned messaged went to server.log

packaging: keycloak file logger

---

.github/workflows/build.yml

Build won't start without specifying a stable branch name in `.github/workflows/build.yml` in the relevant stable branch content

Enable builds on ovirt-engine-4.5.0.z branch

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmBackupsResource.java

Restore the suggestedParent Vm.class in:
```java
collection.getBackups().add(addLinks(map(entity), Vm.class));
```
Previously removed in https://github.com/oVirt/ovirt-engine/pull/174
Bug-Url: https://bugzilla.redhat.com/2075435

restapi: restore suggestedParent

---

ovirt-engine.spec.in

Disable default keycloak integration, the feature needs to be postpone
to oVirt 4.5.1

Disable default keycloak integration

---

packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vdsm/tasks/configure.yml

remove ansible_distribution == 'RedHat' since we already check if the service is running.
fapolicyd < 1.1 doesn't have /etc/fapolicyd/rules.d/,add check if the directory exists.
Backport of https://github.com/oVirt/ovirt-engine/pull/256  and https://github.com/oVirt/ovirt-engine/pull/259 into ovirt-engine-4.5.0.z

host-deploy: condition for adding fapolicy rules

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/MigrateVmCommand.java

When invoking a migration the `cpusets` is sent to VDSM as a list. The index of each list represents the virtual CPU and the value is the physical CPU we are taking. Sorting the values is wrong, as it results a wrong mapping, causing split cores and split sockets.
Bug-Url: https://bugzilla.redhat.com/2075037

Fix wrong dedicated migration assignments

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ConvertDiskCommand.java

If allocation policy or format were not passed to the disk conversion endpoint it will fail to setup monitoring because of NPE.
This patch uses the existing allocation policy or format when it's missing to generate the message.

core: handle missing allocation policy/format when converting

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ConvertDiskCommand.java

To improve readability, set values from the parameters into local variables with the 'asked' prefix and convert the allocation type and volume format to strings only when inserting them to the message properties map.

Refactor ConvertDiskCommand#getJobMessageProperties

---

packaging/setup/ovirt_engine_setup/engine/constants.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/apache/__init__.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/apache/ars_cleanup.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/apache/runner.py

Removal of ansible-runner-service constants from engine_setup.

engine_setup: cleanup after ARS removal

---

backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VdsManager.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/monitoring/HostMonitoring.java

This PR improves handleRefreshCapabilitiesResponse:
1. It first tries to process the response of get-capabilities, if that fails - it immediately logs that and returns an error
2. Only later it tries to get hardware data - if we manage to get a valid response from get-capabilities, it will most likely succeed with that but if not - we log that and continue because we hold the more important data already
3. The code that updates the database and notifies other components that we managed to refresh the host capabilities no longer runs within the same if-block that generates an error related to get-capabilities upon failure (but an appropriate exception would bubble up)

Improve handling of the response of get capabilities

---

backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/VmMapper.java

It was missing and therefore this setting wasn't copied from templates to vm pools.
Bug-Url: https://bugzilla.redhat.com/2076054

Map console disconnect action delay in VmMapper

---

backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/builder/vminfo/LibvirtVmXmlBuilder.java

VDSM does not recognizing `resize and pin NUMA` policy. To let VDSM act
as expected the policy it needs is `manual`, as we have CPU pinning in
this policy and they are part of the shared pool.
Change-Id: Ic742086b8626009e177b0f22c77e268fd501d3c1
Bug-Url: https://bugzilla.redhat.com/2074582

Change resize and pin cpu pinning policy within VM metadata

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AnsiblePackOvaCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/GetFromOvaQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ExportOvaCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ExtractOvaCommand.java

We have added async processing with a timeout as a part of https://github.com/oVirt/ovirt-engine/pull/116 which should use the default Ansible playbook execution timeout specified by ANSIBLE_PLAYBOOK_EXEC_DEFAULT_TIMEOUT engine option. Unfortunately we forgot to convert time units of ANSIBLE_PLAYBOOK_EXEC_DEFAULT_TIMEOUT (specified in minutes) to seconds expected by async keyword in ansible.
Bug-Url: https://bugzilla.redhat.com/2076474

core: Fix time units for ansible async timeout

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AnsiblePackOvaCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/GetFromOvaQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ExportOvaCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ExtractOvaCommand.java

We have added async processing with a timeout as a part of
https://github.com/oVirt/ovirt-engine/pull/116 which should use the
default Ansible playbook execution timeout specified by
ANSIBLE_PLAYBOOK_EXEC_DEFAULT_TIMEOUT engine option. Unfortunately we
forgot to convert time units of ANSIBLE_PLAYBOOK_EXEC_DEFAULT_TIMEOUT
(specified in minutes) to seconds expected by async keyword inn ansible.
Bug-Url: https://bugzilla.redhat.com/2076474

backport to 4.5.0.z: core: Fix time units for ansible async timeount

---

backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/builder/vminfo/LibvirtVmXmlBuilder.java

VDSM does not recognizing `resize and pin NUMA` policy. To let VDSM act
as expected the policy it needs is `manual`, as we have CPU pinning in
this policy and they are part of the shared pool.
Bug-Url: https://bugzilla.redhat.com/2074582

vdsbroker: change resize and pin cpu pinning policy

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendDiskSnapshotResource.java

Fixing GET api/disks/{diskid}/disksnapshots/{snapshotid}:
Return correct snapshot, when more than one snapshot existed
for the disk. Incorrect query (GetAllDiskSnapshots) was used to fetch
a single snapshot. Now using GetDiskSnapshotByImageId instead.
Bug-Url: https://bugzilla.redhat.com/2013696

Fix query in single GET disksnapshot request

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmTemplateCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmTemplateFromConfigurationCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/ImportVmTemplateFromConfParameters.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/ImportVmTemplateParameters.java

When importing a template from OVA we don't go through ImportVmTemplateFromConfiguration and therefore getImageToAvailableStorageDomains() returns an empty map and later we fail with NPE.
This patch changes the fix for https://bugzilla.redhat.com/2043124 to be specific for ImportVmTemplateFromConfiguration and so other import-template flows would not face this issue.
Bug-Url: https://bugzilla.redhat.com/2074916

Fix import template from ova

---

packaging/dbscripts/upgrade/04_05_0100_fix_04_04_0050_set_to_not_null.sql

We have discovered that some users still have some ancient options
present in vdc_options (even though they should be removed now), which
contains NULL in default/actual values.
We have fixed fn_db_change_column_type to properly set NULL/NOT NULL
constraints in https://gerrit.ovirt.org/117448 , but we missed above
that ancient options mentioned above still could exist, so we need to
fix those NULL default/actual values before setiing NOT NULL constrain.
Bug-Url: https://bugzilla.redhat.com/2077387

Handle NULL in default/actual values in vdc_options

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendDiskSnapshotResource.java

Fixing GET api/disks/{diskid}/disksnapshots/{snapshotid}:
Correct href for <parent> and <disk> elements.
1. `<disk>` element was returned without href attribute
2. `<parent>` element had an incorrect href - buildParentHref() was
used, although the element is not related to the parent entity
resource, but rather represents the parent image of the snapshot.

restapi: fix hrefs in single GET disksnapshot request

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/pm/SshSoftFencingCommand.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VdsManager.java

This patch fixes network exception handling and fencing flow logic.
Problems in current code:
1. Hard fencing happens too fast since we waited on number of
attempts <or> grace period, since number of attempts is configured to a
value of "2", grace period was ~20 seconds.
2. VdsManager::isHostInGracePeriod was called periodically from
VdsManager:handleNetworkExeception and from
SsshSoftFencingCommand::checkIfHostBecomeUp which makes the logic
complex in not working as expected
While we have to handle the network exception grace period when the host
is switched to 'connecting' state due to its load regarding number of
running VMs and SPM status, in the case of soft-fencing flow, the host
is already in not-responding status, other host already took the SPM
role and all its running VMs set to …

Fix network exception handling and fencing flow logic.

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/pm/SshSoftFencingCommand.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VdsManager.java

This patch fixes network exception handling and fencing flow logic.
Problems in current code:
1. Hard fencing happens too fast since we waited on number of
attempts <or> grace period, since number of attempts is configured to a
value of "2", grace period was ~20 seconds.
2. VdsManager::isHostInGracePeriod was called periodically from
VdsManager:handleNetworkExeception and from
SsshSoftFencingCommand::checkIfHostBecomeUp which makes the logic
complex in not working as expected
While we have to handle the network exception grace period when the host
is switched to 'connecting' state due to its load regarding number of
running VMs and SPM status, in the case of soft-fencing flow, the host
is already in not-responding status, other host already took the SPM
role and all its running VMs set to …

backport: core: fix network faults handling and fencing flow

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmBackupResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmBackupsResource.java

Partial revert of 152deb4754eac29a2a546257256c63b2f436aa6b
Restoring the suggested parent was not enough and it seems too complicated to get this right for the value it provides
Bug-Url: https://bugzilla.redhat.com/2075435

restapi: revert snapshot link

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/RemoveDiskSnapshotsCommand.java

Currently, when removing individual disk snapshots, they are grouped
by their respective disk_id and are removed together, in the order from
the parent to the child. For example:
A <- S2 <- S1
And we select disks from S1 and S2, S1 will be removed first and then
S2. However, since block commit was introduced, we only do forward
merges, meaning when removing S1, the child S2, will be the one removed
after its contents are merged into S1. So when the operation attempts to
merge S2, it will no longer exist.
This patch fixes the issue by reversing the order of images to start the
operation the other way around.
Bug-Url: https://bugzilla.redhat.com/2070451

core: reverse snapshots list

---

packaging/setup/plugins/ovirt-engine-setup/vmconsole_proxy_helper/pki.py

In commit 35e8f5110af4a84c69eda38a8f5f56d26b050594, a check was added
to renew vmconsole certificates when the CA certificate is newer.  But
the certificates are still not renewed if they are expired or close to
being expired.  Let’s fix it by additionally checking for certificate
expiration.
In order to that, we must check the helper certificate file instead of
key.
Bug-Url: https://bugzilla.redhat.com/1988496

packaging: Renew expiring vmconsole certificates

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmTemplateCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmTemplateFromConfigurationCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/ImportVmTemplateFromConfParameters.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/ImportVmTemplateParameters.java

When importing a template from OVA we don't go through ImportVmTemplateFromConfiguration and therefore getImageToAvailableStorageDomains() returns an empty map and later we fail with NPE.
This patch changes the fix for https://bugzilla.redhat.com/2043124 to be specific for ImportVmTemplateFromConfiguration and so other import-template flows would not face this issue.
Bug-Url: https://bugzilla.redhat.com/2074916

Backport: Fix import template from ova

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ConvertDiskCommand.java

When converting to COW/Prellocated from RAW additional size may be required for the qcow header. We already measure required size, however we only use it for the initial size of the volume which is not used when the target is a preallocated volume on block storage.
This patch uses required size to increase the target volume if it's larger than the current size of the volume to ensure there is enough space to perform the conversion.
Bug-Url: https://bugzilla.redhat.com/2076047

core: adjust volume size when converting to cow/preallocated

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerHttpClient.java

The artifacts created by ansible-runner have the id prefix, which we used to gather the events.
We were listing new artifacts by counting the number of previously processed artifacts and checking the new artifacts from that number as a prefix id. This approach causes multiple issues with async execution where the artifacts are not created in order but there could be a bit of time delay between them. For example, artifact 4 was created before 3.
The new approach fixes this issue by waiting for each file with an id prefix until the playbook finishes or times out.

Ansible-runner: list artifacts one by one

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/util/LinkHelper.java

Currently [LinkHelper#getParent](https://github.com/oVirt/ovirt-engine/blob/6e6ea81436587e6b936de02f0fc1cc48b2544a66/backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/util/LinkHelper.java#L227-L240) may return subclasses even if the parentType exists in the methods list. This makes the returned resource unpredictable as the method list does not have any guaranteed order.
To fix this, this patch tries to match parentType first, and only if it is not in the list it will fallback to a subclass.
In the bug the parent is `Vm`, but since `Backup` also has a reference to the `Snapshot` model it may be chosen over the suggested `parentType` because it's a subclass of `Vm`.
Bug-Url: https://bugzilla.redhat.com/2080728

restapi: prefer parentType over subclasses in getParent

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmCommand.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmsResource.java

we don't normally to this but in case of ImportVmFromConfiguration it makes
some sense to invoke it as a blocking (sync) operation since it doesn't involve
disk operation so if may only have async operation related to vm leases which are
relatively quick. The main reason to do this is that some backup applications
relied on getting Created response and can't cope with Accepted but it also makes
to do that because it is often the case that clients try to start the VM right
after the execution of ImportVmFromConfiguration is completed.
Bug-Url: https://bugzilla.redhat.com/2074112
Signed-off-by: Arik Hadas <ahadas@redhat.com>

Block on execution of ImportVmFromConfiguration

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmCommand.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmsResource.java

we don't normally to this but in case of ImportVmFromConfiguration it makes
some sense to invoke it as a blocking (sync) operation since it doesn't involve
disk operation so if may only have async operation related to vm leases which are
relatively quick. The main reason to do this is that some backup applications
relied on getting Created response and can't cope with Accepted but it also makes
to do that because it is often the case that clients try to start the VM right
after the execution of ImportVmFromConfiguration is completed.
Bug-Url: https://bugzilla.redhat.com/2074112

Block on execution of ImportVmFromConfiguration - backport

---

packaging/bin/pki-create-ca.sh

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2079799

issue internal CA for 20 years

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/host/HostUpgradeManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/HostValidator.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/hosts/HostListModel.java
packaging/ansible-runner-service-project/project/ovirt-host-upgrade.yml
packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-ovn-certificates/tasks/main.yml
packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vdsm-certificates/tasks/main.yml
packaging/bin/pki-enroll-openssh-cert.sh
packaging/dbscripts/upgrade/pre_upgrade/0000_config.sql
packaging/etc/engine-config/engine-config.properties

This should fix some of the problems that users not paying proper attention to certificate expiration warnings and alerts may experience:
- Host certificate lifetimes are much longer now.
- Host certificates are renewed much earlier on host upgrade now.
- Enrolling host certificates in host upgrade actually works.
- It is possible to enroll certificates now when a host is non-responsive.
- ovn-controller is restarted after enrolling certificates.
**Read the corresponding commit messages for more details.**
Not renewing some of the vmconsole certificates will be handled in a separate PR later.
Related bugs:
- https://bugzilla.redhat.com/2079890
- https://bugzilla.redhat.com/2079835
- https://bugzilla.redhat.com/2079901

Improve certificate renewal

---

packaging/bin/pki-enroll-pkcs12.sh
packaging/bin/pki-enroll-request.sh
packaging/setup/ovirt_engine_setup/engine_common/pki_utils.py
packaging/setup/plugins/ovirt-engine-rename/ovirt-engine/pki.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/network/ovirtproviderovn.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/pki/ca.py

Non-web certificates are not subjects to the lifetime limitations
required by web browsers.  Let’s extend the lifetime of non-web Engine
certificates to 5 years (the same value as for the host certificates)
to make the certificate updates much less frequent.
Let’s also drop the check for long certificate lifetime.  All web
certificates should already have the shortened lifetime, otherwise
they wouldn’t work with current browsers.
Bug-Url: https://bugzilla.redhat.com/2079835

certificates: Extend the lifetime of non-web Engine certificates

---

packaging/setup/plugins/ovirt-engine-setup/vmconsole_proxy_helper/pki.py

Checks for vmconsole-proxy-host and vmconsole-proxy-user certificates
status were missing, resulting in those certificates not renewed when
needed.  This patch adds the missing checks.
Bug-Url: https://bugzilla.redhat.com/2066084

certificates: Make sure vmconsole ssh keys are refreshed if needed

---

.automation/build-srpm.sh
.github/workflows/build.yml
ovirt-engine.spec.in

The github action CI build log tends to contain a large amount of
log lines for the transfer progress of downloading dependencies.
This can make a prohibitively large log file to be able to view
it on the github action page.
Use maven 3.6 and the option `--no-transfer-progress` to vastly reduce
the log output to where we can actually scroll the the bottom of the
output on the action's web page.
Note: maven is a separate module on centos 8 stream.  Copr chroot
configs will need to be checked.  Enabling at least maven 3.6 is
requried.

build: use maven 3.6 --no-transfer-progress

---

.copr/Makefile

When building from COPR the project is cloned into temporary directory,
which is not owned by current user. From git 2.35.2 such directory needs
to be marked as safe inn order git commands work correctly.

Mark temp repo directory as safe for COPR 

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/host/HostUpgradeManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/HostValidator.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/hosts/HostListModel.java
packaging/ansible-runner-service-project/project/ovirt-host-upgrade.yml
packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-ovn-certificates/tasks/main.yml
packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vdsm-certificates/tasks/main.yml
packaging/bin/pki-create-ca.sh
packaging/bin/pki-enroll-openssh-cert.sh
packaging/bin/pki-enroll-pkcs12.sh
packaging/bin/pki-enroll-request.sh
packaging/dbscripts/upgrade/pre_upgrade/0000_config.sql
packaging/etc/engine-config/engine-config.properties
packaging/setup/ovirt_engine_setup/engine_common/pki_utils.py
packaging/setup/plugins/ovirt-engine-rename/ovirt-engine/pki.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/network/ovirtproviderovn.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/pki/ca.py
packaging/setup/plugins/ovirt-engine-setup/vmconsole_proxy_helper/pki.py

backport of certificate-related fixes
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2079799
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2079835
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2079890
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2075352
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2079901
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2066084

Backport CA and certificate fixes to 4.5.0.z

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/NewTemplateVmModelBehavior.java

When creating a new template, the initTemplate() method is called after the list of base templates is loaded.
However, if there are no templates other than the Blank template, the list is not loaded and the initTemplate()
method is never called. As a result, the builders from VM to UnitVmModel are never called and the UnitVmModel
is not initialized properly. The attempt to create a new template fails.
This patch calls the initTemplate() method also for the cases when there are no base templates available and the Blank template is the only template present.

webadmin: Fix creating of a new template

---

packaging/setup/plugins/ovirt-engine-setup/ovirt-engine-common/distro-rpm/packages.py

We recently merged a patch to verify that the engine and setup packages'
versions match. This fails on a separate-DWH machine. Fix.
Change-Id: I41b06309e59bbe52dffa30ae2d0f618d9ffca97d

packaging: setup: Do not fail if engine package is missing

---

backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dal/dbbroker/SimpleJdbcCallsHandler.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/ClusterDaoImpl.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/VmDynamicDaoImpl.java
ovirt-engine.spec.in
pom.xml

Backport jdbc

---

packaging/bin/engine-backup.sh.in

This patch introduces a backup/restore functionality for internally
bundled keycloak database.
Depends on: https://github.com/oVirt/ovirt-engine-keycloak/pull/35

packaging: keycloak db backup/restore

---

ovirt-engine.spec.in

As a part of https://github.com/oVirt/ovirt-engine/pull/322 ovirt-engine
now requires postgresql-jdbc >= 42.2.14, whih should be the latest
version available. But unfortunately we forgot to add RPM requires for
this version, which caused issues around upgrade.
Bug-Url: https://bugzilla.redhat.com/2077794

Require postgresql-jdbc >= 42.2.14

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/CopyManagedBlockDiskCommand.java

There is no need to reconstruct the `sourceDisk` as `ManagedBlockDisk` as it is already of this type if the source domain is a Managed Block Storage Domain, and it will fail later on as the conversion method `createManagedBlockDiskFromDiskImage` assigns the target's id to the constructed object which is incorrect, as this is the source disk.

core: fix copying from MBS to image domain

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/OvirtSelectionModel.java

GWT provides NoSelectionModel for cases where the view should not be
updated. This possibility was missing in the Ovirt's higher-order
selection model.

webadmin: add NoSelection mode to OvirtSelectionModel

---

packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/pki/ca.py

In 67e77630f00ea4ff83a4002fac3aa68c1ce61bff we dropped the cehck for 398
validity in certificates. Let's make sure the engine-setup text reflects
the change.

certificates: fix confirmation question

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/CloneVmCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/CloneVmParameters.java

Configuration of a cloned VM may be edited before cloning. In this case
it is passed in CloneVmParameters#vm and should be saved in editedVm
variable and passed to UpdateVmCommand that is executed after cloning.
The code that saves this configuration was incorrectly removed by change
6f143de593b2ce415e7155b8e3a1d634637afa74. This patch restores this code
with one difference: UpdateVmCommand is now executed by CoCo, so
editedVm was moved from CloneVmCommand to parameters.
Change-Id: Id77061ba6749351dcfbe832ad1c38288c6ada479
Bug-Url: https://bugzilla.redhat.com/2080758

core: Use edited VM configuration when cloning

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/HibernateVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/BaseImagesCommand.java

Vdsm often aligns the size of the volume when creating, and the volume
will end up having a different size in the engine than what is on the
storage. This is already handled when a new disk is created but not when
a new snapshot is created.
Since there is already a getVolumeInfo request at the end of snapshot
creation, we can use this opportunity to update the size of the volume
as well.
Bug-Url: https://bugzilla.redhat.com/1852308

core: always update volume size when creating a new image

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/ListModel.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/OvirtSelectionModel.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/UnitVmModel.java

When the BIOS type changed, the graphics list was always reset even though the video type stayed the same.
This was because the setting of the items and selected item was separated in https://gerrit.ovirt.org/c/ovirt-engine/+/118132
This patch goes back to setting the items and selected item at once but making sure that the selection model is not
used to avoid issues fixed by https://gerrit.ovirt.org/c/ovirt-engine/+/118132
Bug-Url: https://bugzilla.redhat.com/2078193

webadmin: Fix reseting of graphics

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/hostdeploy/InstallVdsInternalCommand.java
packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-misc/tasks/tuned_profile.yml

move profile setting from ansible role to engine

fix setting tuned profile

---

packaging/ansible-runner-service-project/project/roles/ovirt-ova-pack/files/pack_ova.py

Fix export OVA-file with installed Python >= 3.8
When OVA exports by host with installed python >= 3.8, it can't be imported back, because in python >= 3.8 tarfile.PAX_FORMAT is used by default.

Use tarfile.GNU_FORMAT in pack_ova.py when create OVA

---

frontend/webadmin/modules/uicompat/src/main/java/org/ovirt/engine/ui/uicompat/LocalizedEnums.java

When testing engine UI with Selenium in the Firefox console we can see:
console.warn: "Mon Apr 25 13:07:02 GMT+000 2022 org.ovirt.engine.ui.uicompat.EnumTranslator
WARNING: Missing Enum resource 'V4_2'. Cannot find constant 'NfsVersion___V4_2';
expecting a method name"
Let's add the java enum entry to match the one defined in the properties
file [1].
[1] https://github.com/oVirt/ovirt-engine/blob/27a8d1c3f678ef9efc9a300da8cc3c8a8c1afef0/frontend/webadmin/modules/uicompat/src/main/resources/org/ovirt/engine/ui/uicompat/LocalizedEnums.properties#L620
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

intl: Add missing localized enum

---

frontend/webadmin/modules/uicompat/src/main/java/org/ovirt/engine/ui/uicompat/LocalizedEnums.java
frontend/webadmin/modules/uicompat/src/main/resources/org/ovirt/engine/ui/uicompat/LocalizedEnums.properties

Add missing localization for DisplayType.bochs enum value.
Change-Id: If5a1328c3ee301d5cb0829c7fd1ec79f1df7f330

webadmin: Add DisplayType.bochs localization

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/MoveDiskCommand.java

if somehow withoption function get null as variablevalue it will not
try to inject variablevalue instead of variableName so this cause the message to
look like this:
Cannot remove Virtual Disk. Disk ${DiskName} is being moved or copied.
so I added validation of getParameters().getNewAlias() and getParameters().getDiskAlias()
and if both are null the LockMessage will be somthing more genaric and will look like this:
Cannot remove Virtual Disk. Related operation is currently in progress. Please try again later.
and if at list one of them is not null I can inject into the message so the message will look like this:
Cannot remove Virtual Disk. Disk vm_disk is being moved or copied.
Bug-Url: https://bugzilla.redhat.com/2039746

core: avoid null value so the ${DiskName} will be injected

---

packaging/dbscripts/common_sp.sql
packaging/dbscripts/upgrade/04_05_0100_fix_04_04_0050_set_to_not_null.sql
packaging/dbscripts/upgrade/pre_upgrade/0000_config.sql

Changing the function that sets a column in the part that turns from
NULL to not NULL to set any found NULL values on the changed column
values to a default value according to the column type.
This script changes also upgrade scripts to pass the v_type new
parameter.
In case that unsupported type is passed, an error is thrown.
Signed-off-by: Eli Mesika <emesika@redhat.com>
Bug-Url: https://bugzilla.redhat.com/2077387
Allow-db-upgrade-script-changes: Yes

db: fix fn_db_change_column_null

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/SetVmTicketCommand.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/VmDynamicDao.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/VmDynamicDaoImpl.java
backend/manager/modules/dal/src/test/java/org/ovirt/engine/core/dao/VmDynamicDaoTest.java
packaging/dbscripts/vms_sp.sql

Previously, we used optimisic locking to see if the user that tries to
connect to the VM can do that or not. However, now that we lock the VM
using VmManager's lock, we don't need that anymore - we can rather
inspect VmDynamic in the command itself to discover it.
Signed-off-by: Arik Hadas <ahadas@redhat.com>

Leverage the VM-lock in SetVmTicket

---

backend/manager/tools/src/main/java/org/ovirt/engine/core/notifier/NotificationService.java
backend/manager/tools/src/main/java/org/ovirt/engine/core/notifier/dao/EventsManager.java
backend/manager/tools/src/main/java/org/ovirt/engine/core/notifier/transport/snmp/Snmp.java
packaging/dbscripts/upgrade/pre_upgrade/0000_config.sql

This bug is a result of applying level 3 security of the new USM
introduced on SNMP V3.
When the Event Notification Service is restarts , it creates a new USM
object but does not update the number of time its was rebooted.
This makes the service suspected by SNMP V3 and it stops getting traps
from it in snmptrapd.
The solution is to add a new configuration value
NotificationServiceBoots which is set by default to 0.
Each time the Event Notification Service is rebooted, this value is
incremented by 1 and stored in the configuration table (vdc_options)
When a new USM object is created on Event Notification Service run
method, it set the number of boots accordint to the persisted value.
This solves the problem and Event Notification Service can be restated
several times and still keep …

persist event notifier service boots

---

packaging/bin/engine-backup.sh.in

This patch includes keycloak related httpd configuration files in backup
paths so that, after restoring from the backup, these files were available
without the need to regenerate them.
Additionally grafana httpd proxy configuration has been added as well
for the same reason.

packaging: fix for keycloak httpd conf.d restore

---

backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/storage/DiskImage.java

A few "DiskImage" data members were overridden with wrong values at the end of Copy Constructor.
The data members are: `CreationDate` &`LastModified` & `ImageStatus`
Seems like the issue started at:
https://gerrit.ovirt.org/c/ovirt-engine/+/3835/4/backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/DiskImage.java#350

Fix "DiskImage" copy constructor

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/CopyImageGroupWithDataCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/CreateVolumeContainerCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/CreateVolumeContainerCommandParameters.java

while coping disk that has incremental backup flag up and set to be preallocated
the new copied disk will change the allocation policy to thin provision.
now it will change the allocation policy to be the same as it was set on the original disk
Bug-Url: https://bugzilla.redhat.com/2072423

core: copy disk will set the correct allocation policy for the new copied disk

---

ovirt-engine.spec.in
packaging/setup/ovirt_engine_setup/engine_common/constants.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/config/aaa.py

Allow setup code to decide/know if Keycloak integration is
supported. In RHV it's not.
Change-Id: I5ec0fee15cc761238989afaec55db9a5aa831778

packaging: setup: Add KeycloakEnv.SUPPORTED

---

backend/manager/modules/dal/src/test/java/org/ovirt/engine/core/dao/UnregisteredDisksDaoTest.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VmReplicateDiskVDSCommand.java

Remove SpringFrameworks's StringUtils implementation with Apache.
Bug-Url: https://bugzilla.redhat.com/2092010

Replace SpringFramework's StringUtils with Apache

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/hostdeploy/InstallVdsInternalCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerHttpClient.java

In some cases play execution is completed, but host deploy process is still running and parsing events.
In such case if the timeout was reached, an attempt to cancel the playbook will fail because the play process
no longer exists.
In cases where the command to cancel the playbook fails, an error will be logged with both host-deploy and
stdout logs.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2087738

don't throw an exception when canceling playbook if play execution was already completed

---

packaging/ansible-runner-service-project/project/roles/ovirt-host-upgrade/tasks/main.yml

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2090670

remove network-scripts-openvswitch 2.11 package before upgrading packages

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/SchedulingManager.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/CpuPinningPolicy.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/comparators/VmsCpuPinningPolicyComparator.java
backend/manager/modules/common/src/test/java/org/ovirt/engine/core/common/businessentities/comparators/VmsCpuPinningPolicyComparatorTest.java

This patch sorts the VM list on schedule phase before doing the
dedicated CPU pinning.
This change tries to reduce the fragmentation that may be caused when
allocating a smaller VM in terms of the policy and CPU topology (a less
restricted) when having a bigger one. Scheduling the smaller VM first
may cause less physical resources needed by the larger VM because we try
to enhance performance in the allocation logic.
Now, the VMs will be sorted based on the policy first and if needed by
the CPU topology, letting the more restricted VM to be scheduled first.
Change-Id: Ia3fc28511c147d43da9cf8d86d50ca17f1e3f0e1

Reduce CPU pinning fragmentation

---

packaging/setup/plugins/ovirt-engine-rename/ovirt-engine/ovn.py
packaging/setup/plugins/ovirt-engine-rename/ovirt-engine/pki.py
packaging/setup/plugins/ovirt-engine-rename/websocket_proxy/pki.py

In commit 67e77630f00ea4ff83a4002fac3aa68c1ce61bff, ‘shortLife’ entity
key was introduced to distinguish between short-lived (e.g. web) and
long-lived (e.g. CA, hosts) certificates.  The key was also used
in ovirt-engine-rename without adding it to the corresponding
entities, resulting in KeyError on ovirt-engine-rename invocation.
This patch fixes the problem by adding the missing keys.
Bug-Url: https://bugzilla.redhat.com/2089803

packaging: Fix KeyError in ovirt-engine-rename certificate handling

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/numa/vm/NumaValidator.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/numa/vm/AddVmNumaNodesCommandTest.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/widget/uicommon/popup/AbstractVmPopupWidget.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/ExistingVmModelBehavior.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/VmModelBehaviorBase.java

This patch will allow setting via UI and API virtual NUMA nodes to a VM
without having the VM pinned to a host. If a `numa_node_pin` is set, the
scheduler will filter out hosts that won't fit to the NUMA pinning.
Otherwise, the VM will start with the set amount of virtual NUMA nodes.
Change-Id: Ia35a95babf3ae6b2d4713c809052be1d6ddede38
Bug-Url: https://bugzilla.redhat.com/2081410

Allow setting virtual NUMA nodes without host pinning

---

backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/HugePageUtils.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/monitoring/HostMonitoring.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VdsBrokerObjectsBuilder.java

So far, the memory usage was calculated in VDSM and the calculation considered hugepages as used memory. As a result, the host with hugepages had high memory usage even though the hugepages were not used.
This patch moves the calculation from VDSM to the engine. This allows to calculate the memory usage differently in various scenarios.
- In the UI, the memory usage calculation includes hugepages so that the user has the full overview of the host memory
- In host monitoring, we issue VDS_HIGH_MEM_USE only for the normal memory and calculation does NOT include hugepages
Bug-Url: https://bugzilla.redhat.com/2006625

engine: Change the memory usage calculation 

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/UnitVmModel.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/VmModelBehaviorBase.java

When VM type is set to Server, if bochs display type is available
according to compatibility version and BIOS type, select it
automatically.
Change-Id: I908a5a090457f8d2ceb165e4b691bd84defe0bb8
Bug-Url: https://bugzilla.redhat.com/1949004

webadmin: Preselect bochs for Server VMs

---

packaging/dbscripts/upgrade/pre_upgrade/0000_config.sql

It was not possible to use Secure CPU types of the old CPUs (Nehalem and Westmere) because they expected
the md_clear flag to be present. However, the microcode update with MDS mitigations was not released for those CPUs.
Bug-Url: https://bugzilla.redhat.com/2079267

engine: Remove md_clear from Nehalem and Westmere

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/CreateSnapshotCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/CreateSnapshotForVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ImagesHandler.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/AuditLogType.java
backend/manager/modules/dal/src/main/resources/bundles/AuditLogMessages.properties

If we ended up not removing the new active volume from the storage
because they may be in-use, do not remove the snapshot from the database
as it may create a discrepancy between the engine DB and the storage,
leading to other issues.
Bug-Url: https://bugzilla.redhat.com/2081294
Signed-off-by: Benny Zlotnik <bzlotnik@redhat.com>

core: do not remove snapshot from DB if related images were not removed

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelper.java

When allocating CPUs for isolate threads we use the maximum freed
socket. This socket is already without pinned CPUs. With that, isolate
threads thinks these cores are free to use, while they are not.
This patch changes the maximum freed socket to contain every CPU within
it, without dropping taken CPUs.
Change-Id: Ic81d93ecd830cea689a8eea4579d6e728c5b2e04
Bug-Url: https://bugzilla.redhat.com/2094415

Don't use vdsm core for isolate threads

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/MigrateVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RemoveVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmOperationCommandBase.java

It was possible to remove a VM during backup, this patch rearranges isDuringBackup() validation method and explictly sets which operations should be blocked or not.
Not blocking:
RunVmCommand
StopVmCommand
MigrateVmCommand
CreateSnapshotForVmCommand
Bug-Url: https://bugzilla.redhat.com/2080718

core: block VM removal during backup

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AddVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/CreateOvaCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmHandler.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmCommandBase.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/SnapshotsManager.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfOvaVmReader.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfOvaVmWriter.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfOvirtReader.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfOvirtWriter.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfProperties.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfReader.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfVmReader.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfVmWriter.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfWriter.java

This patch adds the NUMA nodes list of a VM to the OVA's OVF. It allows
exporting and importing the current VM configuration of virtual NUMA
nodes.
Change-Id: I7cba56cb63020b061e3554805f58f9db653f40fa
Bug-Url: https://bugzilla.redhat.com/2079605

Add NUMA nodes to OVA

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/RemoveSnapshotCommand.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/snapshots/RemoveSnapshotCommandTest.java

Currently removing snapshots on VM during Hybrid backup is not blocked
which allows user to remove the parent snapshot of the auto-generated
snapshot. As a result, the user cannot initiate an image transfer.
Blocking any snapshot removal during active backup fixes this issue,
and also prevents other conflicts. This validation is skipped for
snapshot removal done as part of Hybrid Backup finalization
This PR depends on:
https://github.com/oVirt/ovirt-engine/pull/375
Bug-Url: https://bugzilla.redhat.com/1954427

Block snapshot removal when VM in backup

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/SchedulingManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/pending/PendingCpuCores.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/policyunits/CPUPolicyUnit.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/pending/PendingResourceManagerTest.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/VmCpuCountHelper.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VdsManager.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VmManager.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/monitoring/HostMonitoring.java

After the refactoring of CpuPolicyUnit, we started to calculate required shared CPUs with countThreadsAsCores=true.
This caused that the VMs with RESIZE_AND_PIN cpu pinning policy were not able to migrate between identical hosts when cluster's countThreadsAsCores=false.
This patch changes the calculation in CpuPolicyUnit back to countThreadsAsCores=false and changes that also for the pending resources used in CpuPolicyUnit and the minRequiredSharedCpusCount of the host.
Bug-Url: https://bugzilla.redhat.com/2095259

Fix the calculation of the VM's CPU cores

---

backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/irsbroker/UploadStreamVDSCommand.java

When UploadStreamVDSCommand fails due to network error, the host is
moved to "not responding" status and then fenced. The network error
might happen for different reasons, one of them is timeout, which is
not necessarily a network error. This command uses HTTP rather than
JSON RPC, and the default timeout for HTTP client is set to be 20
seconds, which in some rare cases is not enough for this VDS command
to finish.
This patch prevents sending a network error event when UploadStream
command fails due to network error, which in turn prevents
disconnecting and fencing of the host, so that this error will not
have such an impact on otherwise healthy system.
Bug-Url: https://bugzilla.redhat.com/2070045

core: ignore UploadStreamVDSCommand network failure

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AddGraphicsAndVideoDevicesCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmHandler.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/DisplayType.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VmBase.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VmStatic.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfReader.java
packaging/dbscripts/upgrade/04_05_0290_change_default_display.sql

Until now the default video device was QXL, and the graphics were set to
SPICE+VNC. But, in the future QXL won't be supported - both on EL9 and
if one wishes to migrate to Openshift Virtualization.
In the API, QXL is left for now. As we have only one video device and
QXL supports both VNC and SPICE inputs. On a following patch, the
default display will change in API based on whether it supported.
Currently missing some corner cases for blank template, if it's set with a
different video/graphic devices than QXL.
Change-Id: Id96b469144a87454b882744bc798aa83aa9ae715
Bug-Url: https://bugzilla.redhat.com/1976605

core: default VGA video for new VMs

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/CloneImageGroupVolumesStructureCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ImagesHandler.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/lsm/LiveMigrateDiskCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/FeatureSupported.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/CloneImageGroupVolumesStructureCommandParameters.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/vdscommands/VmReplicateDiskParameters.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/jsonrpc/JsonRpcVdsServer.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/IVdsServer.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/NullVdsServer.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VmReplicateDiskStartVDSCommand.java

Adding image initial size calculation for Live Storage Migration flows for disks
that reside on Block Storage Domain.
Relevant for cluster version 4.7 or above.
Bug-Url: https://bugzilla.redhat.com/1958032

Live Storage Migration - correctly calculate image initial size

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/ConfigureConsoleOptionsQuery.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/ConfigureConsoleOptionsQueryTest.java

FIPS can be enabled on a host without the corresponding parameter in
the kernel command line.  In such a case, the host expects username in
the VNC display ticket.  But Engine inserts username only when the
FIPS parameter is in the kernel command line and VNC connection
doesn’t work is such a case.
To fix this, let’s check in Engine for what the host says about FIPS
rather than for the kernel command line parameter.

core: Check for real FIPS when adding username to a VNC ticket

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmFromExternalProviderCommand.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/exportimport/ImportVmFromExternalProviderCommandTest.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/ValidationUtils.java

When importing a VM, aliases are generated for all imported disks. To
comply with oVirt naming convention for disk aliases, we need to replace
all illegal characters that may appear in imported disk names.
Change-Id: I4f54a3fd8e31799d8ca33d2f4413e82f452ebabd
Bug-Url: https://bugzilla.redhat.com/1904962

core: Replace all illegal chars in disk aliases

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/backup/HybridBackupCommand.java

Even if we were unable to remove the auto-generated snapshot, the backup will be considered successful. This patch produces the right audit log entry to indicate the backup did not fail.

core: produce successful event if backup finished successfully

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/AbstractDiskModel.java

Screenshot: https://imgur.com/a/blTWJqy
When creating a new disk on the UI, the incremental backup flag should
be checked by default.
Bug-Url: https://bugzilla.redhat.com/1915029

webadmin: Mark 'Incremental Backup' flag by default

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/UnitVmModel.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/VmModelBehaviorBase.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/instancetypes/NonClusterModelBehaviorBase.java

When switching back from headless VM, the default is SPICE/QXL.
This patch changes it to VNC/VGA.
Change-Id: Ic63dbf22e3cd199fc782dc8e8963c8899478a6ae

UI: Default VGA when backing from headless

---

packaging/dbscripts/vm_templates_sp.sql
packaging/dbscripts/vms_sp.sql

After changing type of vm_static.console_disconnect_action_delay field
in the database to int, need to change type of stored procedure
parameters accordingly.
Change-Id: Ibaa4351cf863cf2032ca3a6605ff8da7ed553397
Bug-Url: https://bugzilla.redhat.com/2076053

core: Change type of console_disconnect_action_delay parameters

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/SchedulingManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelper.java

When we allocate CPUs we are basing upon the list we return back. This
is correct for the scheduling phase. But now we run the same logic on
canSchedule. There, when having a group of VMs, we are basing on the
cpuTopology list, not the list we selected to allocate. The overtaken
CPU wasn't released from the pinning itself and that harmed the
canSchedule logic for VM groups.
Also, when grouping the VMs, when the group is having an affinity set,
it is reordered. Therefore, it is required to sort them there as well.
Change-Id: Idcae90fed953c4798f2c4bf8893bff0a1b7086ea

Release CPUs reminders

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommand.java

When downloading a disk that is an overlay of a template, take only a shared lock on the disk and skip the locked disk validation, this would allow downloading disks of thin VMs without failing on the disk being locked

Use shared lock on disks for dependent VMs

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommand.java

We changed the lock of disks that are being downloaded to be a shared
lock instead of an exclusive lock. Here we change the message that is
associated with this lock to be the same as we use for the exclusive lock
in case of upload-disk, which is more informative.

Change lock message of disks being downloaded

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AnsibleCallback.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AnsibleCommandBase.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/AnsibleCommandParameters.java

If the ansible playbook execution happened faster than the engine, we
may get a successful status and the correct number of events. In that
case we may skip the event processing in the ansible callback. Which may
lead us to wrong data returned to the command itself.
Change-Id: I432938a7fc241701eb260c1fbc460d1de7149092

Set initial event number for async ansible commands

---

backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/NumaPinningHelper.java

When a VM with NUMA is set with hugepages with a size that is different than the one reported by the host, the
running of the VM fails with NPE in NumaPinningHelper.
This patch fixes the NPE.

engine: Fix NPE when misconfiguring NUMA with hugepages

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/HotSetNumberOfCpusCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/UpdateVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmManagementCommandBase.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/UpdateVmCommandTest.java

This patch prevent the user from hotplugging CPU when the VM is set with
exclusive pinning as we don't support it. Currently it will add a new
CPU without any pinning, which breaks the VM configuration.
With this patch, it won't be allowed and the user will be noticed.
Change-Id: Ie8d32b9e85879e6764bab63399c3d5762ba806db

Block hot plug CPU with exclusive pinning

---

packaging/setup/ovirt_engine_setup/engine_common/pki_utils.py
packaging/setup/ovirt_engine_setup/remote_engine.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/pki/ca.py
packaging/setup/plugins/ovirt-engine-setup/vmconsole_proxy_helper/pki.py

Bug-Url: https://bugzilla.redhat.com/2093954
Bug-Url: https://bugzilla.redhat.com/2096862
Bug-Url: https://bugzilla.redhat.com/2097725

setup: Allow renewing certificates during the warning period

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/quota/QuotaCRUDCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/quota/RemoveQuotaCommand.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/quota/RemoveQuotaCommandTest.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/QuotaCRUDParameters.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendQuotaResource.java
backend/manager/modules/restapi/jaxrs/src/test/java/org/ovirt/engine/api/restapi/resource/BackendQuotaResourceTest.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/quota/QuotaListModel.java

Added missing method for ${QuotaName} substitution in the audit log
message for RemoveQuotaCommand.
Change-Id: I9826e1965b7faf8dc46afa80d1218ae49fc4a34b
Bug-Url: https://bugzilla.redhat.com/2018412

core: Quota name in audit log when deleting quota

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ConvertDiskCommand.java

The actual size of a volume is reduced when converting the disk from COW/preallocated to COW/thin on a block storage domain is not updated, making it seem like disk consumes more than it actually does.
This patch updates the actual size after conversion.
Bug-Url: https://bugzilla.redhat.com/2086561

core: update actual size after conversion

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/SnapshotsManager.java
frontend/webadmin/modules/uicompat/src/main/java/org/ovirt/engine/ui/uicompat/NextRunFieldMessages.java
frontend/webadmin/modules/uicompat/src/main/resources/org/ovirt/engine/ui/uicompat/NextRunFieldMessages.properties

When creating a VM configuration string from the VM object, the NUMA Node list was always updated from the database. This caused that the new settings for the VM were not saved into the NEXT_RUN snapshot.
Bug-Url: https://bugzilla.redhat.com/2099225

engine: Save updated Numa Nodes into NEXT_RUN snapshot

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/hostdeploy/InstallVdsInternalCommand.java

Previous fix [1] used the wrong method to calculate the number of HE hosts
[1] https://gerrit.ovirt.org/c/ovirt-engine/+/118221/
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2027087

warn user when there are too many he hosts

---

frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/widget/uicommon/storage/DisksAllocationView.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/storage/DisksAllocationModel.java

Screenshot: https://imgur.com/a/w1dMuCU
This patch fixes the alignment under Resource Allocation > Disk
Allocation, when cloning a VM.
The disk panel is being first created as part of the view initiation.
Determining the DC quota level (disabled/enforced) affects the number of
columns appear in the disk allocation view.
Since updating the quota happens later (not as part of initialization),
The columns' width can't be changed unless re-creating the disks lists
in the view, so the view needs to be created with the updated width.
Bug-Url: https://bugzilla.redhat.com/2081546

webadmin: fix alignment on Resource Allocation popup

---

packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/config/aaajdbc.py

This patch changes default ovirt admin email address to one required
(hardcoded) by grafana so that oVirt SSO works when Keycloak integration
is disabled.

packaging: unify ovirt admin user email

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmHandler.java

The next-run snapshot is created in a compensation context, which causes
it to be removed if something fails.
But the previous (if exists) next-run snapshot is removed outside the
compensation context.
This causes the VM's to lose its next-run snapshot if for example an
UpdateCluster fails.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2094729
Signed-off-by: Jean-Louis Dupond jean-louis@dupond.be

Delete next-run snapshot in a compensation context

---

packaging/setup/ovirt_engine_setup/engine/constants.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/network/ovirtproviderovn.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/pki/ca.py

When Engine CA certificate file is removed and then engine-setup with
certificate renewal is run, engine-setup may fail with the following
error:
[ ERROR ] Failed to execute stage 'Misc configuration': [Errno 2] No such file or directory: '/etc/pki/ovirt-engine/keys/ovn-sdb.key.nopass'
The problem is that
otopi.plugins.ovirt_engine_setup.ovirt_engine.network.ovirtproviderovn.Plugin._upgrade,
which requires the presence of the OVN keys,
may be run before
otopi.plugins.ovirt_engine_setup.ovirt_engine.pki.ca.Plugin._miscUpgrade,
which generates them if previously asked for that by
otopi.plugins.ovirt_engine_setup.ovirt_engine.network.ovirtproviderovn.Plugin._misc_pki.
Let’s ensure correct ordering of these three actions and also set up
OVN renewal if self._provider_installed is true, since …

setup: Make sure OVN key files are available before accessing them

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmCommandBase.java

When we are importing a VM that is pinned to a host, and the host is not present in the cluster where the VM should be imported, the host pinning is cleared as well as the cpu pinning string. However, the cpu pinning policy was not updated and remained MANUAL causing the import to fail when inserting the VM into the database. 
This patch updates the cpu pinning policy to NONE when cpu pinning string is cleared during import.
Bug-Url: https://bugzilla.redhat.com/2104115

core: set correct policy when reseting cpu pinning string

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/GetArchitectureCapabilitiesQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/HibernateVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/CreateLiveSnapshotForVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/CreateSnapshotForVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/RestoreAllSnapshotsCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/SnapshotsManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/TryBackToAllSnapshotsOfVmCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/ActionUtils.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/FeatureSupported.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/CreateSnapshotForVmParameters.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/config/ConfigValues.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/queries/ArchCapabilitiesParameters.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/widget/uicommon/popup/vm/VmSnapshotCreatePopupWidget.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/dataprovider/AsyncDataProvider.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/VmSnapshotListModel.java
packaging/dbscripts/upgrade/04_05_0300_remove_vdc_option_IsMemorySnapshotSupported.sql

If the VMs are set to restore memory, we would now set them to
Suspended status so they'll be treated as VMs that were hibernated
(e.g., create next-run snapshots when their configuration changes)
Bug-Url: https://bugzilla.redhat.com/1257644

Set VMs that preview memory snapshots to suspended

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelper.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelperTest.java

We now release using unPin the VdsCpuUnit we need. This is good for
`dedicated` policy. When we are handling `isolate-threads` policy we
need to release the whole core. Otherwise the engine thinks it's taken.
Change-Id: I0b028e0dc5db72f5ef3099059f355d975a81fc90
Bug-Url: https://bugzilla.redhat.com/2103620

Release core reminders for isolate threads

---

backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/FeatureSupported.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/config/ConfigValues.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/builder/vminfo/LibvirtVmXmlBuilder.java
packaging/dbscripts/upgrade/pre_upgrade/0000_config.sql
packaging/etc/engine-config/engine-config.properties

If VM is configured with VGA display type, use virtio-vga driver for it.
This behaviour may be configured through osinfo database.
Change-Id: I2476286e90cd84b51e35bd3170affeaee1924951
Bug-Url: https://bugzilla.redhat.com/2038694

core: Use virtio-vga driver for VGA

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommand.java

Uploading image into MBS will be block inside TransferDiskImageCommand validation

core: Block MBS Image upload

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/lsm/LiveMigrateDiskCommand.java

Initializing a HashMap with double-brace create an inner class and the
value of diskImagesMap will be a HashMap wrapped in:
```
org.ovirt.engine.core.bll.storage.lsm.LiveMigrateDiskCommand$1
```
Instead of just a HashMap, and LiveMigrateDiskCommand is not deserializable which will prevent ovirt-engine from starting when it tries to reload command_entities

core: do not use double-brace initialization for parameter value

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/MaintenanceNumberOfVdssCommand.java

Added a comment to MaintenanceNumberOfVdssCommand to avoid confusion
about VM affinity types checked in validation and execution phases of
the command.
Change-Id: I583f720ce1f82ca4f23541b987665cce4f0a11d9

core: Comment about VM affinity validation on migration

---

packaging/setup/plugins/ovirt-engine-common/base/remote_engine/remote_engine.py

When engine-setup fails on dnf repositories download, the followup
cleanup fails with
[ ERROR ] Failed to execute stage 'Clean up': 'NoneType' object has no attribute 'cleanup'
This patch fixes it and allows the cleanup finish normally.

setup: Don’t fail cleanup on empty remote engine environment

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/templates/TemplateInterfaceListModel.java

As the Blank template is not associated with any DC/Cluster, it's not possible to assign any network vNIC profile to it. Therefore, the New button should be disabled.
Bug-Url: https://bugzilla.redhat.com/2100444

webadmin: Disable New on Networks tab for Blank

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/MaintenanceVdsCommand.java

In MaintenanceVdsCommand, if migrateAllVms() returned successful return
value, do not check isValid() and do not copy validation messages from
it.
Change-Id: I9c38423c88b7a4e8a84d6187835abe490278def5
Bug-Url: https://bugzilla.redhat.com/2108000

core: Ignore isValid() == false, if migration succeeded

---

backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/monitoring/HostMonitoring.java

The memory usage number in VDS_HIGH_MEM_USE warning should be the usage of normal memory, not the total usage of normal memory and hugepages memory. This patch corrects the memory usage value in the audit log.
Bug-Url: https://bugzilla.redhat.com/2101503

engine: Fix incorrect value in audit log warning

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/network/vm/ActivateDeactivateVmNicCommand.java

Lack of a lock in ActivateDeactivateVmNicCommand allows several
instances of hot plug and unplug requests to run in parallel causing an
inconsistent in vNIC status as well as libvirt failing the requests due
to non-unique aliases. This patch adds a lock to the command so that
each instance of the command has to finish before the next one starts.
Bug-Url: https://bugzilla.redhat.com/2084530
Change-Id: I93ac9f1f12f34526ad10b9a49790c3a2689e8c4d

core: vnic hot un\plug - avoid race

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleExecutor.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerClient.java

- core: remove redundant set
- core: fix lastEventId tracking

fix lastEventId tracking

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/commands/AffinityGroupCRUDCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/AffinityValidator.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/commands/AddAffinityGroupCommandTest.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/commands/EditAffinityGroupCommandTest.java

When an affinity conflict occurs, the hosts or VMs participating in
the conflict are reported by their ids.  This is accurate but not very
user friendly, especially in the web UI dialog.  Let’s report the
conflicting entities by their names instead.
We must retrieve the names from the corresponding DAOs.  In theory,
AffinityGroup’s should contain entity names corresponding to the ids,
but this doesn’t hold and the names are often missing there.
Due to the DAO access, AffinityValidator.checkAffinityGroupConflicts
can no longer be static.  And because AffinityValidator is a
singleton, it cannot be used in tests as it is (AFAICT).  That means
we have to mock AffinityValidator.checkAffinityGroupConflicts in some
tests and give up on testing that method there.
Bug-Url: …

core: Report names rather than ids in affinity conflicts

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/commands/AffinityGroupCRUDCommand.java

Added null check in AffinityGroupCRUDCommand.getClusterId() to avoid NPE
when the affinity group does not exist. The command fails in the
validation later.
Change-Id: I473969a190ab5db1577615d28970d72e10341846
Bug-Url: https://bugzilla.redhat.com/2067104

core: Fix NPE on invalid affinity group ID

---

backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VdsManager.java

Previously, once the CPU topology was initialized in the VdsManager, it was not possible to change it without
restarting the engine. There are 2 use cases:
1. When adding a new host, the manager is created, but no CPU topology has been reported yet. As a result, the host
would act as if it does not support exclusive pinning until the engine is restarted.
2. Changing the CPU topology of the host (not a common scenario, but happens during development when using hosts in a virtual machine).
This patch updates the CPU topology in the VmManager if the state of the host changes and the CPU topology has not been initialized yet.
Bug-Url: https://bugzilla.redhat.com/2104858

core: update cpuTopology on status changes

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmPoolsResource.java

Display type passed in VmPool.vm should be converted to a list of
graphic types and passed in parameters to AddVmPoolCommand.
Change-Id: I44303911c4228b66b3b8a081be774dd51188321e
Bug-Url: https://bugzilla.redhat.com/2106349

restapi: Pass display type from VmPool.vm to AddVmPoolParameters

---

ovirt-engine.spec.in
pom.xml

This patch bumps jsonrpc java version to fix an issue with hosts stayed
forever in 'connecting' state after an attempt to reconnect with expired
SSL certificates
Bug-Url: https://bugzilla.redhat.com/2090645

packaging: Bump vdsm-jsonrpc-java to 1.7.2

---

packaging/ansible-runner-service-project/project/roles/ovirt-host-upgrade/tasks/main.yml

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2104408

Clean cache before upgrading packages

---

packaging/bin/pki-enroll-openssh-cert.sh
packaging/bin/pki-enroll-request.sh

let's keep these files non-writable to any random user
Bug-Url: https://bugzilla.redhat.com/2088446

pki: make openssl database non-writable for others

---

packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vm-console-certificates/tasks/main.yml

ovirt-vmconsole is running under its own user and need access to
certificates. This only worked till now since the certificates were
mistakenly opened to others, but now it prevents sshd to acess its host
key

ansible: make ovirt-vmconsole host certificate readable

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AnsibleCallback.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleExecutor.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerClient.java

- ansible: Remove unused things
- AnsibleRunnerClient: make 'mapper' a scoped object

Ansible runner cleanup

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/connection/ISCSIStorageHelper.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/connection/StorageServerConnectionCommandBase.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/connection/AddStorageServerConnectionCommandTest.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/connection/UpdateStorageServerConnectionCommandTest.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/StorageServerConnectionDao.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/StorageServerConnectionDaoImpl.java
packaging/dbscripts/storages_san_sp.sql

Currently when adding/updating iSCSI storage server connection, there
is a validation that checks if a duplicate connection exists by iqn,
address, port, portal, username and password. This allows creating
two storage connections with the same iqn, address and port, but with
different portals.
There cannot be two portals with the same iqn-address-port, thus
creating two such connections does not make sense and will lead to
errors connecting the host to storage.
This change fixes the validation to fail add/update request if
connection with the same iqn-address-port combination exists
Bug-Url: https://bugzilla.redhat.com/2079903

Change iSCSI storage connection validation to properly avoid duplications

---

backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/VmCommonUtils.java
frontend/webadmin/modules/uicompat/src/main/java/org/ovirt/engine/ui/uicompat/NextRunFieldMessages.java
frontend/webadmin/modules/uicompat/src/main/resources/org/ovirt/engine/ui/uicompat/NextRunFieldMessages.properties

It is not possible to hot plug CPUs when using exclusive CPU pinning. Instead of failing on the backend, the CPU is now listed as "Changes that require Virtual Machine restart" instead of "Changes that can be applied immediately" in the "Pending Virtual Machine changes" dialog.
Bug-Url: https://bugzilla.redhat.com/2097717
Bug-Url: https://bugzilla.redhat.com/2111088

Do not allow hot plug CPU with exclusive pinning

---

backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/monitoring/VmAnalyzer.java

When the VM was powering UP and had the next run configuration, the cold reboot did not work. It had several reasons that have been fixed in this patch:
1. the VM was just cleared based on `getVmManager().getPowerOffTimeout()`
2. the `VmAnalyzer:proceedDisappearedVm` did not have `RebootInProgress` case and the default one was executed.
However, the code never reached the `setColdRebootFlag()` as the VM was listed as `asyncRunning` and scheduled for rerun.
3. the next run config was never applied as the VM was present in `asyncRunning` and never added to `movedDown` list.
Bug-Url: https://bugzilla.redhat.com/1912911

engine: fix reboot on powering up VM

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/CloneImageGroupVolumesStructureCommand.java

The current check doesn't use measureVolume if the volume is a leaf, but there is no reason to do this if the disk is not attached to a running a VM.
This patch checks if the disk is attached to a running VM before checking if the volume is a leaf to ensure it's measured correctly.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2104806

core: measure unattached disks

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AttachUserToVmFromPoolAndRunCommand.java

Added missing job properties in AttachUserToVmFromPoolAndRunCommand that
were appearing as <UNKNOWN> values.
Change-Id: I1c6446e275cbb266a2093f65a4cadc08c489ea26
Bug-Url: https://bugzilla.redhat.com/2016341

core: Add missing AttachUserToVmFromPoolAndRun job properties

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AnsibleCallback.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleClientFactory.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleExecutor.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleReturnValue.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerClient.java

eliminate wrong use of singleton's class properties - they get
overwritten by each run. Whole state is now passed through
AnsibleReturnValue object consistently.

ansible runner client refactoring

---

packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/network/ovirtproviderovn.py

Due to incorrect staging and missing dependencies, OVN certificates
are not renewed if there are no other certificate renewals needed.
This patch fixes it by changing when OVN certificate info to PKI
entities is added.  It must be done:
- In STAGE_CUSTOMIZATION rather than STAGE_MISC.  STAGE_CUSTOMIZATION
is where we ask for certificate renewal if needed.
- After the OVN plugin attributes are initialized so that the event
condition doesn’t crash on a missing attribute.
- Before certificate renewal check is performed.
It must be also done after
self.environment[oenginecons.PKIEnv.ENTITIES] is initialized but that
happens in STAGE_INIT, which is run early so no change is needed
here.  Note that we cannot add the OVN certificate info there in
STAGE_INIT because we don’t know yet whether OVN …

packaging: Make sure OVN certificates are renewed when needed

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/GetDiskAndSnapshotsByDiskIdQuery.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/disk/AbstractGetDisksAndSnapshotsQueryTest.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/disk/GetDiskAndSnapshotsByDiskIdQueryTest.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/StorageServerConnections.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendHostResource.java
backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/StorageLogicalUnitMapper.java

```xml
<lun_storage id="36001405b55de9787c7a41e88d3a5ba0c">
<logical_units>
<logical_unit id="36001405b55de9787c7a41e88d3a5ba0c">
<address>10.35.0.156</address>
<discard_max_size>4194304</discard_max_size>
<discard_zeroes_data>false</discard_zeroes_data>
<disk_id>cd89659f-9983-4e0a-b0b4-a487f8cc995f</disk_id>
<lun_mapping>1</lun_mapping>
<paths>0</paths>
<port>3260</port>
<product_id>iscsi-target-01</product_id>
<serial>SLIO-ORG_iscsi-target-01_b55de978-7c7a-41e8-8d3a-5ba0c528d6fe</serial>
<size>32212254720</size>
<target>iqn.2003-01.org.dhcp-0-156.iscsi-target</target>
<vendor_id>LIO-ORG</vendor_id>
<volume_group_id>oc4SkF-prGc-55uP-RtWI-pGz9-IyLI-D9AFu3</volume_group_id>
</logical_unit>
</logical_units>
</lun_storage>
```

core,restapi: report iscsi server address and port for direct LUNs

---

pom.xml

Following important changes on api-metamodel has been done since 1.3.7:
* Change asciidoc link-generation
https://github.com/oVirt/ovirt-engine-api-metamodel/pull/28
* Add RPM packaging
* Switch from log4j backend to java.util.logging backend
Following important changes on api-model has been done since 4.5.10:
* Image I/O Proxy is replaced by ovirt-imageio
https://bugzilla.redhat.com/2042401
* Deprecate VmPool.display attribute
https://bugzilla.redhat.com/2106349
* Updated documentation to SystemOptionService
https://bugzilla.redhat.com/1974974
* Add TpmSupport to OperatingSystemInfo
https://github.com/oVirt/ovirt-web-ui/issues/1596
* Change slashes to hyphens in xrefs
https://github.com/oVirt/ovirt-engine-api-model/pull/80

Bump metamodel to 1.3.9 and model to 4.5.11

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/DiskStatisticalQuery.java

the inputs of create function for DATA_READ_OPS  and DATA_WRITE_OPS
from GAUGE to COUNTER and from StatisticUnit.SECONDS to
StatisticUnit.NONE
Bug-Url: https://bugzilla.redhat.com/2018796

restapi: Change StatisticKind to COUNTER and StatisticUnit to NONE

---

packaging/ansible-runner-service-project/project/ovirt-host-reconfigure-ovn.yml
packaging/ansible-runner-service-project/project/ovirt-host-upgrade.yml
packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-facts/tasks/host-os.yml

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2107250

update variables to make host upgrade work with rhel7

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/lsm/LiveMigrateDiskCommand.java

In case of Live Storage Migration failure during `LiveDiskMigrateStage.CLONE_IMAGE_STRUCTURE` the remove image cleanup was skipped.
It should be performed in order to free the already allocated space on the target Storage Domain.
Bug-Url: https://bugzilla.redhat.com/2102149

Perform cleanup after insufficient free space error during LSM

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AnsibleImageMeasureCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AnsiblePackOvaCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/GetFromOvaQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/MaintenanceVdsCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RemoveVdsCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ExportOvaCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ExtractOvaCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/gluster/CreateBrickCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/host/HostUpgradeManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/hostdeploy/HostEnrollCertificateInternalCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/hostdeploy/InstallVdsInternalCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleCommandConfig.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleExecutor.java

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2104939

add ssh port to inventory

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/ColdMergeSnapshotSingleDiskCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/RemoveSnapshotSingleDiskLiveCommand.java

When trying to remove a snapshot which was already removed before
and image merged, but not removed from the DB for some reason -
the RemoveSnapshot command fails and the snapshot and images stay in
the DB and cannot be removed.
The reason for this is that during RemoveSnapshotSingleDiskLiveCommand
the DestroyImage command fails (since the image does not not exist),
thus the whole command fails, and the snapshot/image are not removed
from the DB.
In the ColdMerge case, the ColdMergeSnapshotSingleDiskCommand fails
already at the PrepareMerge stage.
In this change, for both Live and Cold merge - we first check that the
Destination image (or the Top Image) exists on storage with
GetVolumeInfo. If it does not, we conclude that it was already merged
and removed, and proceed to finishing the …

fix snapshot removal when image already merged

---

backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfWriter.java

TPM device has its own method writing its OVF entry.  But as a special
device, it’s written the second time to OVF among other devices.  When
such an OVF is imported, the VM has two TPM devices, which is not
allowed by libvirt and the VM fails to start.
This patch prevents writing the second TPM device entry to OVF.
Bug-Url: https://bugzilla.redhat.com/2112702

core: Prevent writing TPM device twice to OVA

---

ovirt-engine.spec.in

RHV 4.4 SP1 requires RHEL 8.6 EUS and it's not supported on RHEL 8.7+
Bug-Url: https://bugzilla.redhat.com/2108985

RHV 4.4 SP1 requires RHEL 8.6 EUS

---

.github/workflows/build.yml

In the CI github action, checkout the PR head commit instead of the
`actions/checkout@v2` default of the PR merge commit.  The practical
effect of this change is the exported artifacts snapshot suffix will
contain the commit id of the last commit on the PR instead of the
magic github generated merge commit.

ci: Checkout the PR head, not the github merge commit

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/RemoveSnapshotSingleDiskLiveCommand.java

Call to GetVolumeInfo was added to RemoveSnapshotSingleDiskLive
command before performing the steps, in order to check if the
Destination image (or the Top Image) exists on storage. It was added
to the procedure, which is determining the initial merge step during
the first run of performNextOperation.
GetVolumeInfo is a synchronous call, and calling it from
performNextOperation can block the callback thread which may block
other commands from making progress. This change moves the procedure
of setting the initial merge step back to executeCommand(), like it
is in ColdMergeSnapshotSingleDisk command

LiveMerge: move getVolumeInfo to executeCommand

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleCommandConfig.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleExecutor.java

Cluster upgrade is running on engine locally, not on hosts. Let's supply
"localhost" to make sur that log file and inventory is created.

ansible: fix cluster upgrade

---

backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/VmDeviceCommonUtils.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfReader.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfWriter.java

TPM device has its own special handling and thus is not a special
device with general properties.

core: Don’t mark TPM device as special

---

packaging/ansible-runner-service-project/project/roles/ovirt-ova-pack/files/pack_ova.py

We missed one place in https://github.com/oVirt/ovirt-engine/pull/374.
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

pack_ova: Use tarfile.GNU_FORMAT

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/CertificationValidityChecker.java
backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/EngineLocalConfig.java

There was added an ovirt-provider-ovn certificate validity check as
a part of https://github.com/oVirt/ovirt-engine/pull/576 but
unfortunately the path to certificate file was wrong and as this
certificate is optional (it doesn't exists on setup with OVN integration
disable), the certificate validity checker didn't raise any error even
for setups with OVN integration enabled and ovirt-provider-ovn
certificate going to expire soon.
Bug-Url: https://bugzilla.redhat.com/2097560

Fix checking ovirt-provider-ovn certificate validity

---

packaging/setup/ovirt_engine_setup/engine_common/database.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/db/configuration.py

We currently have two sets of configuration items for PG: One is common
to all DBs, another is specific to the engine. Unite them, by moving the
engine-specific set to the common one.
Cases where this is relevant:
1. Right now, 'engine-backup --mode=restore --provision-all-databases'
does not configure the engine-specific items. This causes a next run of
'engine-setup' (which is mandatory) to prompt, asking whether to
configure them.
2. Trying to pre-create DBs using provisiondb, like I am now trying [1],
leaves postgresql.conf without the engine-specific set. This is worse
than in (1.), as the code prompting/asking works only with non-new
databases. It's not a real issue for [1] specifically, because I can
easily do this there, but decided it's better to patch engine-setup
directly.
This …

packaging: setup: Always use formerly-engine-specific PostgreSql conf

---

pom.xml

When you build ovirt-engine on a system where a language other than
English is setted, Maven Surefire uses it a default language and select
MessageBundles according to this, making some tests fail.
This commit set English and US explicitly as default language and
country in the POM, allowing Surefire to pick the right properties files
during tests.
Bug-URL: https://bugzilla.redhat.com/show_bug.cgi?id=2120066

Fix build on system using a language other than English.

---

.github/workflows/build.yml

Add ovirt-engine-4.5* string to branches specification to remove the
need to allow running CI on every new 4.5 branch in future

Allow running CI on master and any ovirt-engine-4.5* branch

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/profiles/DiskProfileHelper.java

When we create the memory or metadata disks they are a result of live
snapshot with memory or hibernation command. In some cases the user can
own the VM, including the option to execute the above command but he may
not have the disk profile permission to add those disks.
This patch will skip the permission validation in those cases, allowing
a user that owns the VM and capable of executing the command to not fail
on the underlying addDisk command.
Change-Id: Ib04048d652c8d98df84ffccc4babd71730b218dc
Bug-Url: https://bugzilla.redhat.com/1565183

Skip disk profiles validation on memory disk

---

ovirt-engine.spec.in
packaging/setup/ovirt_engine_setup/cinderlib/constants.py
packaging/setup/ovirt_engine_setup/constants.py
packaging/setup/ovirt_engine_setup/engine/constants.py
packaging/setup/ovirt_engine_setup/engine_common/constants.py
packaging/setup/ovirt_engine_setup/engine_common/database.py
packaging/setup/ovirt_engine_setup/provisiondb/constants.py
packaging/setup/plugins/ovirt-engine-common/base/core/filter_secrets.py
packaging/setup/plugins/ovirt-engine-common/base/core/show_doc_text.py
packaging/setup/plugins/ovirt-engine-setup/cinderlib/db/connection.py
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/db/connection.py

When running engine-setup with an answer file generated by a previous
interactive engine-setup, without this patch, we log some secrets
unfiltered. Fix this:
- Require a new otopi that provides LOG_FILTER_QUESTIONS.
- Add an attribute 'asked_on' for constants. If a constant is_secret,
require setting asked_on, to a list of question names that might
change/set it.
- Add a field CREDS_Q_NAME_FUNC to the various *DB_ENV_KEYS. This field
should point at a function that should return the question name for a
particular field.
- Change getCredentials to not get a parameter queryprefix for
constructing the question names, instead relying on CREDS_Q_NAME_FUNC.
- Add functions *question_name for both passing as CREDS_Q_NAME_FUNC and
for asked_on.
- And finally: Patch filter_secrets.py to also loop …

packaging: setup: Filter from logs secrets from otopi answer files

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/CreateSnapshotFromTemplateCommand.java

In some scenarios CreateSnapshotFromTemplateCommand fails after creation
of the record in the images table. In this case the record should be
removed together with other DB records related to the disk.
Change-Id: I201b49b9acd052c733c4d418abbac3b16c9431d5
Bug-Url: https://bugzilla.redhat.com/2110351

core: Remove image if CreateSnapshotFromTemplateCommand failed

---

pom.xml

org.eclipse.m2e:lifecycle-mapping plugin is used only when the project
is edited in Eclipse IDE, it's not relevant for other maven invocation.
Unfortunately it emits bellow warning during maven execution:
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0
So this patches moves the plugin invocation into its own profile, which
is automatically invoked only when a project is loaded into Eclipse
IDE.

Move lifecycle-mapping plugin into Eclipse specific profile

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/RemoveSnapshotCommand.java

Try to remove snapshot even in case of low Storage Domain disk space.
Otherwise, when remove snapshot is performed at the end of Live Storage Migration operation, the `RemoveSnapshotCommand` fails on validation and leaves 3 chunks' snapshot (7.5 GiB) unreleased.
Additionally, the LSM operation is reported as failed, though the "move" part actually succeeded.
Due to extra 3 chunks that are temporary used during LSM flow, we might temporary fall below disk space threshold.
Currently not only that the code leaves unreleased an almost 8 GiB "junk", but it also leaves the Storage Domain in unhealthy low-space state which blocks other operations and requires a manual intervention instead of quietly recovering from this temporary low disk space situation by performing the  proper cleanup.
Before …

Skip thresholds validation for remove snapshot

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/ReduceImageCommand.java
backend/manager/modules/dal/src/main/resources/bundles/ExecutionMessages.properties

Bug-Url: https://bugzilla.redhat.com/2120040

Add missing execution job message for ReduceImage

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/storage/UploadImageModel.java

When a user will try to upload ISO file the Incremental Backup will be 
set to false and uncheckable 
Bug-Url: [https://bugzilla.redhat.com/2120228](https://bugzilla.redhat.com/2120228)

ui: Changed Incremental Backup from default true to false

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/VmListModel.java

When we create a new template, it is not possible to change almost any value defined in the original VM.
Therefore, it does not make sense to validate on the UI, because the user cannot do anything if the validation fails.
Moreover, if the validation fails, there is no way to display the results to the user - the dialog just stays open with no message displayed.
When we remove the validation on the UI, we will depend on the backend validations and if something fails, the backend error messages would be displayed to the user.
Note that the exception from this is the check for the duplicate name, that is performed separately and will be preserved as frontend check. In this case, the name field is marked as not valid with proper error message.

webadmin: remove the validation for a new template

---

packaging/setup/ovirt_engine_setup/constants.py
packaging/setup/plugins/ovirt-engine-common/base/remote_engine/remote_engine.py

Some actions need to be executed in closeup stage before remote engine
is cleaned up, so the clean up action need to have unique name.
Bug-Url: https://bugzilla.redhat.com/2122174
Corresponding DWH change: https://github.com/oVirt/ovirt-dwh/pull/49

setup: Put unique name to remote engine cleanup event

---

backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/VmDeviceCommonUtils.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/RunOnceModel.java

If a VM contains a single disk not marked as bootable, RunVmCommand
allows to boot OS from this disk. But RunOnce ignores this disk when
setting the boot order. This patch fixes this inconsistence.
Change-Id: Ia5652bb1549bdd5205284be355e3a2903fb6e9f1

core: Allow RunOnce for single non-bootable disk

---

backend/manager/dependencies/common/pom.xml
backend/manager/dependencies/tools/pom.xml
backend/manager/extensions-tool/pom.xml
backend/manager/modules/aaa/pom.xml
backend/manager/modules/auth-plugin/pom.xml
backend/manager/modules/bll/pom.xml
backend/manager/modules/builtin-extensions/pom.xml
backend/manager/modules/common/pom.xml
backend/manager/modules/dal/pom.xml
backend/manager/modules/enginesso/pom.xml
backend/manager/modules/extensions-manager/pom.xml
backend/manager/modules/logger/pom.xml
backend/manager/modules/restapi/interface/definition/pom.xml
backend/manager/modules/restapi/jaxrs/pom.xml
backend/manager/modules/restapi/pom.xml
backend/manager/modules/utils/pom.xml
backend/manager/modules/vdsbroker/pom.xml
backend/manager/tools/pom.xml
backend/pom.xml
build-tools-root/ovirt-checkstyle-extension/pom.xml
ear/pom.xml
frontend/brands/ovirt-brand/pom.xml
frontend/pom.xml
frontend/webadmin/modules/frontend/pom.xml
frontend/webadmin/modules/gwt-aop/pom.xml
frontend/webadmin/modules/gwt-common/pom.xml
frontend/webadmin/modules/pom.xml
frontend/webadmin/modules/uicommonweb/pom.xml
frontend/webadmin/modules/webadmin/pom.xml
pom.xml

- Clean up dependencies and plugins versions
- Clean up backend/manager/dependencies/common/pom.xml
- Clean up backend/manager/modules/aaa/pom.xml
- Clean up backend/manager/modules/auth-plugin/pom.xml
- Clean up backend/manager/modules/common/pom.xml
- Clean up backend/manager/modules/dal/pom.xml
- Clean up backend/manager/modules/restapi/interface/definition/pom.xml
- Clean up backend/manager/modules/restapi/pom.xml
- Clean up backend/manager/modules/vdsbroker/pom.xml
- Clean up backend/pom.xml
- Clean up ear/pom.xml
- Clean up frontend/brands/ovirt-brand/pom.xml
- Clean up frontend/webadmin/modules/gwt-common/pom.xml
- Clean up frontend/webadmin/modules/pom.xml
- Remove specific dependencies/plugins versioning

cleanup pom dep versioning

---

backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/serialization/json/JsonObjectDeserializer.java

DeserializationFeature.READ_ENUMS_USING_TO_STRING causes jackson to
deserialize enums using their toString implementation, however, this
implementation may have been overridden to returns a value that does not
match Enum#name(), causing deserialization to fail. Because of this it
would make more sense to use the default, which uses Enum#name() as it
is cannot be overridden.
Additionally, the corresponding serialization config
(WRITE_ENUMS_USING_TO_STRING), which will make jackson use different
methods for serialization and deserialization.
Bug-Url: https://bugzilla.redhat.com/2123008

core: do not use DeserializationFeature.READ_ENUMS_USING_TO_STRING 

---

frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/widget/uicommon/storage/DisksAllocationView.java

DisksAllocationView#addDiskList wasn't prepared for getting a model
without disks sets (i.e., 'disks' is null) and since https://github.com/oVirt/ovirt-engine/commit/50e0bb96a17ddb18fb065963683d37198609dfd2 this
might happen, therefore proper handling (treating this case as if an
empty list of disks is set) is added to DisksAllocationView#addDiskList.
Bug-Url: https://bugzilla.redhat.com/2121083
Signed-off-by: Arik Hadas <ahadas@redhat.com>

Fix error when changing cluster of diskless vms

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/lsm/LiveMigrateDiskCommand.java

Exactly the same call to `setStoragePoolId()` is already performed in `init()`, see [1].
So I see no reason why the same code should be executed again in `validate()`, especially that `validate()` is designed for other purposes.
[1] https://github.com/oVirt/ovirt-engine/blob/ovirt-engine-4.5.2/backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/lsm/LiveMigrateDiskCommand.java#L143
Signed-off-by: Pavel Bar <pbar@redhat.com>

Removing a duplicate "setStoragePoolId()" call at the "LiveMigrateDiskCommand" class

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ImageTransferUpdater.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/storage/ImageTransferPhase.java

Do not update the phase if the incoming phase is invalid
Bug-Url: https://bugzilla.redhat.com/2092816

core: validate transfer phase

---

ovirt-engine.spec.in

Change-Id: If99406a66beebe49e2759214df4d831f3a275688

packaging: spec: Conflict with ansible-core >= 2.13

---

packaging/setup/plugins/ovirt-engine-common/base/remote_engine/remote_engine_manual_files.py

Make remote_engine_manual_files.py match the behavior of remote_engine_root_ssh.py, and so make 'copy_from_engine' return a bytes object, not str.
This should fix the bug that [1] was supposed to fix, but [1] only fixed it for the 'manual files' mode and broke paramiko/ssh.
[1]
https://github.com/oVirt/ovirt-dwh/commit/885d65f0594dee08a48fbe48bdf697de7bcceb6b
Change-Id: I32cd8aff5e851fb053b2cd5b8237455ce2230a35

packaging: setup: remote_engine: manual_files: Read as binary

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/MoveOrCopyDiskCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/CopyImageGroupCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/MoveImageGroupCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/lsm/LiveMigrateDiskCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/LiveMigrateDiskParameters.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/MoveOrCopyImageGroupParameters.java

Commands performing actions on 2 Storage Domains (source & destination) use `MoveOrCopyImageGroupParameters` or its subclasses.
Until `MoveOrCopyImageGroupParameters` there was only 1 Storage Domain used - the one that the action was performed on.
The support for source Storage Domain ID was added in `MoveOrCopyImageGroupParameters`, while the already existing (in `StorageDomainParametersBase` superclass) Storage Domain ID was implicitly used as the destination Storage Domain ID.
Some additional support to easier reference source & destination Storage Domains' IDs was added in `LiveMigrateDiskParameters`.
Still there were a few issues - a missing clear destination Storage Domain ID setter and also inconsistent naming between the classes.
Refactoring the code to add the full and …

Refactor LiveMigrateDiskParameters & MoveOrCopyImageGroupParameters

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/GetDiskSnapshotByImageIdQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/GetAllDiskSnapshotsQuery.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/storage/Disk.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendDiskSnapshotResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendDiskSnapshotsResource.java

If User send REST API request  for ovirt-engine/api/disks/{diskid}/disksnapshots?include_active&include_template he will get this  incorrect href back \<parent href="/ovirt-engine/api/disks/{diskid}" id="{parentid}"/\>.
Now it will get correct output that will look like this \<parent href="/ovirt-engine/api/disks/{parentdiskid}/disksnapshots/{parentid}" id="{parentid}"/\>.
Bug-Url: https://bugzilla.redhat.com/2013697

restapi: incorrect href for parent href

---

ovirt-engine.spec.in

In be73877c I made the engine conflict with a too-old dwh, < 4.5.5. Eventually the changes we need there are in 4.5.6.
Without this, engine-setup (4.5.3 engine, 4.5.5 dwh) fails with:
***L:ERROR Internal error: asked_on must be set when is_secret is set Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/otopi/main.py", line 141, in execute
self.context.loadPlugins()
File "/usr/lib/python3.6/site-packages/otopi/context.py", line 803, in loadPlugins
self._loadPluginGroups(plugindir, needgroups, loadedgroups)
File "/usr/lib/python3.6/site-packages/otopi/context.py", line 112, in _loadPluginGroups
self._loadPlugins(path, path, groupname)
File "/usr/lib/python3.6/site-packages/otopi/context.py", line 69, in _loadPlugins
self._loadPlugins(base, d, groupname)
File …

packaging: spec: Conflict with dwh < 4.5.6

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VdsEventListener.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/IVdsEventListener.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/ResourceManager.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/monitoring/VmAnalyzer.java

The latest available guest tools version is figured out by analyzing ISO
disks available on ISO and data storage domains. The list of available
ISO disks is cached and this cache is refreshed when user queries the
list of images on a storage domain. At that moment, the latest guest
tools version is refreshed and the guest agent installation hint
(presented to the user) is updated.
But ISO cache refresh does not happen after a new guest agent is
installed. That's why the guest agent installation hint is still shown
after installing the latest guest agent in the VM.
To fix that, this patch adds ISO cache refresh when the list of
applications for a particular VM is changed.
Change-Id: I6c25a97ae14cc40d073b3873c6bae9db3216204d
Bug-Url: https://bugzilla.redhat.com/1983401
Bug-Url: …

core: Refresh ISO cache when new guest agent installed

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/GetDiskSnapshotByImageIdQuery.java

There was a [fix](https://github.com/oVirt/ovirt-engine/compare/80af2c8e5ea9d81558508eb3602c435ce4bc570c..c3f83f67af84df51cceb337777b599d8f301ca3a) from @ahadas that was somehow missed in the final version that was merged.
Adding this as an addition to the already merged patch by @ArtiomDivak (see [1]).
[1] PR: https://github.com/oVirt/ovirt-engine/pull/549
Bug-Url: https://bugzilla.redhat.com/2013697

Fix "GetDiskSnapshotByImageIdQuery" to be more null-safe

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/TryBackToAllSnapshotsOfVmCommand.java

This is a followup fix for https://github.com/oVirt/ovirt-engine/pull/653 (based on a [comment review](https://github.com/oVirt/ovirt-engine/pull/653#pullrequestreview-1109114915) ) by including the metadata volumes (in addition to memory ones) when checking if an active snapshot is set with memory for restoring.
Signed-off-by: Sharon Gratch <sgratch@redhat.com>

core: fix checking if an active snapshot is set with memory for restoring purpose

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/policyunits/VmLeasesReadyFilterPolicyUnit.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/RunVmCommandTest.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/policyunits/VmLeasesReadyFilterPolicyUnitTest.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/VmManager.java

This patch looks like a hack but as we don't have enough time
to do that more cleanly for 4.5.3, we go this way in order to
address a significant issue with disaster recovery:
When registering an highly avilable VM on the secondary site
and trying to start it, the latter operation may fail due to
filtering hosts that didn't report a proper state for the
storage domain on which the VM lease was created.
The proposed solution is to add the VM to HaAutoStartVmsRunner
so we would keep trying to start it in that case. Specifically,
when we fail to find a host due to the filterng that is done
by VmLeasesReadyFilterPolicyUnit on an attempt to start the
VM by a request we get from outside (i.e., not internal
execution), we switch the VM to Down state with exit reason
that reflects an Error and …

Handle absent of lease SD when starting ha vm

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/MoveOrCopyDiskCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/lsm/LiveMigrateDiskCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/storage/StorageDomainValidator.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/disk/MoveOrCopyDiskCommandTest.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/lsm/LiveMigrateDiskCommandTest.java

Update Live Storage Migration flow validation to require additional 3 chunks (approximately 8 GiB) of free space on the destination Storage Domain.
Bug-Url: https://bugzilla.redhat.com/2116309

Require extra 8 GiB free space on the destination Storage Domain in the LSM flows

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/AbstractBackendActionableResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/AbstractBackendCollectionResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/AbstractBackendResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendStorageDomainVmResource.java
backend/manager/modules/restapi/jaxrs/src/test/java/org/ovirt/engine/api/restapi/resource/BackendTemplateResourceTest.java

In https://github.com/oVirt/ovirt-engine/commit/38d5120a50c5fde814f229117922d658d3bff531 we've changed add VM from configuration to
be a blocking/sync operation. Here we do something similar for
register-vm, setting it to blocking/sync by default, for the
same reason - this operation doesn't involve copying the disks,
only add-lease is asynchronous and it is a relatively short
operation, so the caller won't wait much and at the end of the
call the VM is ready to be used.
This is particularly important for disaster recovery as we try
to start highly available VMs right after registering them. It
might have been better to change the disaster recovery scripts
to specify async=false, but that would require more efforts.
That change revealed an issue with the tests of ExportVmTemplate
since it …

Make register-vm a sync operation

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/lsm/LiveMigrateDiskCommand.java

This patch fixes an issue when the engine is restarted during LSM, the command gets stuck.
The cause of this issue was that EngineLocks were passed to LiveMigrateDiskCommand, and from there to CreateSnapshotCommand in the executeCommand() stage. There the locks are released, and reacquired later on before snapshot remove phase. If the engine was restarted during CreateSnapshot phase - both the CreateSnapshot and LiveMigrateDisk commands resumed, running reacquireLocks, and then before the Snapshot Remove phase, LiveMigrateDiskCommand attempted to reacquire locks again, getting stuck.
In this patch we override reacquireLocks method in LiveMigrateDisk command, doing nothing, and then the locks on Disk and VM are acquired separately before the snapshot remove phase
Bug-Url: …

LSM: fix locking on restart

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/UnitVmModel.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/VmListModel.java

In https://github.com/oVirt/ovirt-engine/pull/621, the validation of a new template was removed from the UI in assumption that the backend can validate the template properly. However, the backend does not contain validation for the name and if the name is not provided, it fails on inserting null to a not null database column. This patch adds the name validation back to the fronted.

webadmin: Add validation to new template

---

ovirt-engine.spec.in

1. Remove no longer needed MEAD remains
2. Exclude building on s390x and ppc64le hosts because of jsass
dependency on native library

Optimize RHV parts of spec file

---

Makefile

Building engine in dev env should always use online maven build. Offline
maven build should be used only during RPM build.

Do not use offline build in dev env

---

backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/crypt/EngineEncryptionUtils.java
backend/manager/modules/utils/src/test/java/org/ovirt/engine/core/utils/crypt/EngineEncryptionUtilsTest.java
packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/network/ovirtproviderovn.py

Use OAEP with SHA256 and MGF1 padding in password encryption and
decryption during authenticating with ovirt-ovn-provieder on el9
deployments where FIPS is enabled.
This change should not be merged until all code paths using the modified
EngineEncryptionUtils facility are evaluated for correctness and until
this modification is made active only when FIPS is enabled.
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>
Change-Id: Ie895d2249716d6aafd64d79ae2d61083181b9703

core: use fips-compatible padding for provider passwords

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/domain/DetachStorageDomainFromPoolCommand.java

This patch adds a call to OvfDataUpdater#triggerNow right after detaching
a storage domain in order to clean VMs/templates that were removed when
the storage domain was detached from the vm_ovf_generations table
immediately rather than in the next cycle we update the OVFs.
In 78d21eee4 we fixed an issue that caused importing VMs/templates with
old (stale) data. That fix could very well also fix the issue described
in the below mentioned bug, however, it is safer to also ensure that the
removed VMs/templates are also removed from the vm_ovf_generations table
to stop having old/stale data in the database that should never be used.
Bug-Url: https://bugzilla.redhat.com/1705338
Signed-off-by: Arik Hadas <ahadas@redhat.com>

Trigger OvfDataUpdater when detaching a storage domain

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/StorageHandlingCommandBase.java

Fix Storage Domain detach flow.
There is no need to write the OVF data related to VMs & VM templates into the `unregistered_ovf_of_entities` DB table.
That causes in certain scenarios a stale data to be left there.
This table is correctly filled with up-to-date data during Storage Domain attach flow.
Bug-Url: https://bugzilla.redhat.com/1705338

Fix SD detach flow ("unregistered_ovf_of_entities" DB table)

---

backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/crypt/EngineEncryptionUtils.java

We have added new encryption/decryption method for OVN provider password
as a part of https://github.com/oVirt/ovirt-engine/pull/677
Unfortunately there was an error during password decryptio due to the
implementation differencies between Python and OpenJDK.

Fix padding issue when decrypting OVN provider password

---

backend/manager/modules/enginesso/src/main/java/org/ovirt/engine/core/sso/service/TokenCleanupService.java

- Fix RPM build warnings around cinderlib
- Use oVirt buildcontainer image
- Enable EL9 builds
- Use offline maven build
- Install maven metadata without xmvn
- adjust bump_release.sh
- [DO NOT MERGE] log refresh_token

keycloak: cache refresh_token 

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/UpdateClusterCommand.java

When editing a cluster's CPU or version, an update of the underlying VMs and templates is performed.
If any of them has numa enabled, the update cluster command would fail because paramters's updateNuma = null is changed to updateNuma = true in UpdateVmCommand.
Tnis patch makes it explicit that we are not updating the numa by setting updateNuma = false parameter.

engine: Fix update cluster with numa VMs

---

ovirt-engine.spec.in

1. Remove code in comments, such as '#if' or '#raw', which was
supported only in maven-build
2. Remove maven options which were needed only when building in MEAD

Optimize RHV Manager build options in spec file

---

ovirt-engine.spec.in

- Skip validation of build environment
- Increase GWT localWorkers to 2

backport: fix cbs el9 build issue

---

backend/manager/modules/enginesso/src/main/java/org/ovirt/engine/core/sso/service/TokenCleanupService.java

if there are multiple sessions for the same user (i.e. with different
scopes) we only get the refresh_token for the first established one and
we cannot invalidate it on first logout, so let's keep keycloak session
active until the one that established it first logs out

keycloak: do not invalidate session without refresh_token

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AddVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmPoolMonitor.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/snapshots/CreateSnapshotCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/AddDiskCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ImagesHandler.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/utils/ovf/OvfManager.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/VM.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/storage/DiskVmElement.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/VmDeviceCommonUtils.java
backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/ImageDao.java
backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/builder/vminfo/LibvirtVmXmlBuilder.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/widget/uicommon/popup/vm/VmRunOncePopupWidget.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/BootSequenceModel.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/RunOnceModel.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/UnitVmModel.java

Fix minor problems in the code causing IDE warnings.
Change-Id: I4801da93eadbf42bc000b6456aabefa113954f1c

core: Fix IDE warnings

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/RemoveDiskCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/RemoveDiskParameters.java

Adding callback to RemoveDiskCommand so that it would wait for RemoveImageCommand to finish, incl. removing the image from the DB. This fixes an issue where RemoveDisk job was marked as FINISHED before the image was actually removed from the DB.
Bug-Url: https://bugzilla.redhat.com/2137207

core: add callback to RemoveDiskCommand

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/RemoveDiskCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/RemoveDiskParameters.java

Backporting commit from https://github.com/oVirt/ovirt-engine/pull/715

Backport: add callback to RemoveDiskCommand

---

.github/workflows/build.yml

Unfortunately latest version is broken, so let's use older one until the fix is there

limit ansible-lint version to 6.8.3

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AddUserProfilePropertyCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/GetUserProfilePropertiesByUserIdQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/GetUserProfilePropertyByNameAndUserIdQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/GetUserProfilePropertyQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RemoveUserProfilePropertyCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/UpdateUserProfilePropertyCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/UserProfileValidator.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/AddUserProfilePropertyCommandTest.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/RemoveUserProfilePropertyCommandTest.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/UpdateUserProfilePropertyCommandTest.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/validator/UserProfileValidatorTest.java

Before, every admin user has full write access to user profiles of other users. 
After this patch only super users will be able to modify user profiles of other users.
Admin users will have read only access.

Restrict user profile write acces to owner and super user

---

frontend/webadmin/modules/frontend/src/main/java/org/ovirt/engine/ui/frontend/Frontend.java
frontend/webadmin/modules/frontend/src/main/java/org/ovirt/engine/ui/frontend/NotificationHandler.java
frontend/webadmin/modules/frontend/src/main/java/org/ovirt/engine/ui/frontend/NotificationStatus.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/widget/uicommon/tasks/ToastNotification.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/presenter/overlay/TasksPresenterWidget.java

Before, in order to display a toast notification, the component needed
direct access to NotificationPresenterWidget.
With this patch this restriction has been removed. The notification
handler registers itself in the Frontend which allows public access.

webadmin: display toast notifications via Frontend

---

.automation/build-rpm.sh

dnf builddep needs root, let's try a passwordless sudo in case the
automation is using a different user. Sudo needs to be configred
separately.

add sudo for non-root automation builds

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/utils/VmDeviceUtils.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/VmManagementParametersBase.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/VmSnapshotListModel.java

- core: Add missing items in VmManagementParametersBase copy constructor
- frontend: Add TPM parameter when cloning a VM from a snapshot
- core: Update TPM device in parameters

Backport: Add missing copies of TPM parameters

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/StorageHandlingCommandBase.java

If getImagesList fails due to an error we should not continue with attaching the SD assuming there no disks on the storage as this will corrupt the OVF stores.
Instead fail the attach operation and have the user retry once the issue is resolved.
Bug-Url: https://bugzilla.redhat.com/2126602

core: fail storage domain attach if getImagesList fails

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RemoveVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/RemoveAllVmImagesCommand.java

Previously, RemoveVm and RemoveAllVmImages didn't have a callback so they didn't wait for all instances of RemoveImage to finish before finishing RemoveVm and therefore the job of RemoveVm may have been completed while the images are still locked in the database.
Now, RemoveVm is completed after RemoveImage completes and the images are removed from the database.

Fix monitoring of RemoveVm

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RemoveVmCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/RemoveAllVmImagesCommand.java

Previously, RemoveVm and RemoveAllVmImages didn't have a callback so they didn't wait for all instances of RemoveImage to finish before finishing RemoveVm and therefore the job of RemoveVm may have been completed while the images are still locked in the database.
Now, RemoveVm is completed after RemoveImage completes and the images are removed from the database.

Fix monitoring of RemoveVm (backport)

---

.automation/build-rpm.sh
.automation/build-srpm.sh
Makefile
version.mak

GitHub builds had duplicated dates in RPM names. Also swapped date and
githash so that RPMs are time-sorted.

build: fix release_suffix for GH builds

---

.automation/build-srpm.sh

we run with bash -e, need to make sure all return codes are 0.

build: fix return code when SUFFIX is empty

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/GetVmFromOvaQuery.java

When importing an OVA that is not originated in oVirt the VM will diappear
after detaching its storage domain. The vm will not be seen in the import VM
tab. From now on even if the imported VM is no originated in ovirt it could
be imported after detaching the storage domain.

core: Imported VM missing in OVFSTORE

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/ReduceImageCommand.java

ReduceImage is an asynchronous operation. Previously, on positive flow we logged a successful execution message on both 'execute' and 'end-action' phases of the command. The former is incorrect and therefore dropped (we typically log a message that says that the operation has started at this point but we don't plan for another translation cycle so it's not added as part of this change).

Prevent duplicate audit logs for ReduceImage

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/ReduceImageCommand.java

ReduceImage is an asynchronous operation. Previously, on positive flow we logged a successful execution message on both 'execute' and 'end-action' phases of the command. The former is incorrect and therefore dropped (we typically log a message that says that the operation has started at this point but we don't plan for another translation cycle so it's not added as part of this change).
Bug-Url: https://bugzilla.redhat.com/2141437

Prevent duplicate audit logs for ReduceImage (backport)

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/GetVmFromOvaQuery.java

When importing an OVA that is not originated in oVirt the VM will diappear after detaching its storage domain. The vm will not be seen in the import VM tab. From now on even if the imported VM is no originated in ovirt it could be imported after detaching the storage domain.
Bug-Url: https://bugzilla.redhat.com/2028242

core: Imported VM missing in OVFSTORE (backport)

---

.github/workflows/build.yml

Use pip3.9 to install ansible-lint after engine switched to use
ansible-core-2.13+

Fix pip version for ansible-lint

---

pom.xml

Following changes are included in api-model 4.6.0:
* Add loongarch64 architecture type

Bump model to 4.6.0

---

.github/workflows/build.yml

following the recommendation change in upload-rpms-action let's use latest commit

github: switch upload-rpms-action to main

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendClustersResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendDataCentersResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVnicProfilesResource.java

When a user is asking for data via the API with some filter (name of the required entity for example), we should call implicitly the search engine from one hand to implement the filter and from the other hand we are getting all the entities that the user can access according to the permissions via a pre-defined query.
Given the search and the query results, both are intersected to given a result that matches the given filter with the user authorization.
In AbstractBackendCollectionResource we have two signatures for getBackendCollection method:
protected List<Q> getBackendCollection(QueryType query, QueryParametersBase queryParams) protected List<Q> getBackendCollection(QueryType query, QueryParametersBase queryParams, SearchType searchType)
The 1st just brings the query results, teh 2nd …

Search correctly entities with user role

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AddVmTemplateCommand.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/VmListModel.java

Previously, the backend (AddVmTemplate) set new templates with the vm-init configuration of the VM that they were created from. This prevented users from creating templates with modified vm-init configuration or without vm- init configuration from VMs that are set with vm-init. Users could either change the VM first or modify the created template to achieve this.
Now, the backend respects the vm-init configuration that is specified by clients. While the handling of vm-init in REST-API works well, the UI did not pass the vm-init configuration of the VM that templates were created from. Therefore, the webadmin is changed to load the vm-init configuration of the VM that a template is created from and pass it to the backend now.

Set new templates with specified vm-init

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendClustersResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendDataCentersResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVnicProfilesResource.java

When a user is asking for data via the API with some filter (name of the
required entity for example), we should call implicitly the search
engine from one hand to implement the filter and from the other hand we
are getting all the entities that the user can access according to the
permissions via a pre-defined query.
Given the search and the query results, both are intersected to given a
result that matches the given filter with the user authorization.
In AbstractBackendCollectionResource we have two signatures for getBackendCollection method:
protected List<Q> getBackendCollection(QueryType query, QueryParametersBase queryParams)
protected List<Q> getBackendCollection(QueryType query, QueryParametersBase queryParams, SearchType searchType)
The 1st just brings the query results, teh 2nd …

backport: Search correctly entities with user role (#766)

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerClient.java

Title - Fix NPE during ova import
Issue - During ova import, if event node is null, engine log has error as well as NPE
Fix - Check eventNode for the null value
Signed-off-by: Shubha Kulkarni <shubha.kulkarni@oracle.com>

Fix NPE during ova import

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/CreateImageTemplateCommand.java

Previously, all template disks were created with backup mode = NONE regardless of the backup mode of the disks of the VM that the template is created from.
Now the backup mode would propagte from the VM disks to the template disks when their format is qcow2. If the template disks are created as raw their backup mode would be NONE. Enabing to create template disks with incremental backup enabled from VM disks that are raw is outside of the scope of this change.

Propagate backup mode to template disks

---

.automation/build-srpm.sh

Mark current directory as safe for git to be able to parse git hash when
building .src.rpm

Fix EL9 build complaining about git unsafe directory

---

backend/manager/tools/src/main/java/org/ovirt/engine/core/config/entity/ConfigKeyFactory.java

Setting some of the properties returned an error [1]
This is a regression caused by https://bugzilla.redhat.com/show_bug.cgi?id=2089299
[1] https://lists.ovirt.org/archives/list/users@ovirt.org/message/OPH7BHGBGWMECQKRXY6GW3YGZR73JK2D/
Signed-off-by: dangel101 <dangel101@gmail.com>

fix setting value to engine config properties

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/AnsibleRunnerCleanUpService.java

- add debug logging to AnsibleRunnerCleanUpService
- executing ansible runner artifacts clean up at fixed rate

B2151549 ansible runner artifacts not cleaned up

---

backend/manager/tools/src/main/java/org/ovirt/engine/core/config/entity/ConfigKeyFactory.java

Setting some of the properties returned an error [1]
This is a regression caused by https://bugzilla.redhat.com/show_bug.cgi?id=2089299
[1] https://lists.ovirt.org/archives/list/users@ovirt.org/message/OPH7BHGBGWMECQKRXY6GW3YGZR73JK2D/
Signed-off-by: dangel101 <dangel101@gmail.com>

backport: fix setting value to engine config properties

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/AnsibleRunnerCleanUpService.java

Ansible-Runner artifacts are cleaned up periodically according to the properties
configured in engine-config:
AnsibleRunnerArtifactsLifetimeInDays: How many days artifacts will be kept before
they are cleaned up
AnsibleRunnerArtifactsCleanupCheckTimeInHours: The periodic time to execute the clean up
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2151549
Signed-off-by: dangel101 <dangel101@gmail.com>

backport: executing ansible runner artifacts clean up with fixed delay

---

packaging/ansible-runner-service-project/project/roles/gluster-brick-create/tasks/main.yml

The issue is a regression caused by ansible-list changes in
https://github.com/oVirt/ovirt-engine/pull/658
Fixes: https://github.com/oVirt/ovirt-engine/issues/804

Fix double quote issue when creating gluster brick

---

packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/network/ovirtproviderovn.py

Align with previous work [1] to make engine-setup use default system crypto policy when deploying ovirt-provider-ovn and make the provider use the policy.
This should allow engine to execute OVN flows on el9stream.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1179273
Change-Id: I778dab737fd59b1e19e71c7a20071578253ef5d0

Use system crypto policy for OVN encrypted connections

---

ovirt-engine.spec.in

OvS 2.17 and OVN 2.19 are the lowest supported versions on EL9, so we
need to bump the requirements. But OvS 2.15 and OVN 2021 are the
supported versions on EL8, no changes there.

Bump OvS to 2.17 and OVN to 2.19 on EL9

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/AnsibleRunnerCleanUpService.java

Adding info regarding the file's creation time in days, current date in days
and the config value artifacts life time is set to, for easier debugging
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2151549
Signed-off-by: dangel101 <dangel101@gmail.com>

backport: add debug info

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/AnsibleRunnerCleanUpService.java

WE have handled only IOException, but when a file cannot be removed due
to insufficient permissions then SecurityException is raised and because
of that we didn't continue with the removal of other directories.
Bug-Url: https://bugzilla.redhat.com/2151549

Don't stop clean up when a file cannot be removed

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/AnsibleRunnerCleanUpService.java

WE have handled only IOException, but when a file cannot be removed due
to insufficient permissions then SecurityException is raised and because
of that we didn't continue with the removal of other directories.
Bug-Url: https://bugzilla.redhat.com/2151549

backport: Don't stop clean up when a file cannot be removed

---

i18n/pom.xml
pom.xml

Upgrade snakeyaml to 1.33 to resolve all existing security issues
with previous versions

Upgrade snakeyaml to 1.33

---

pom.xml

Bump jackson to 2.12.7, which is available in the latest EAP

Bump jackson to 2.12.7

---

ovirt-engine.spec.in
packaging/ansible-runner-service-project/project/ovirt-host-reconfigure-ovn.yml
packaging/ansible-runner-service-project/project/roles/ovirt-provider-ovn-driver/tasks/configure.yml

it's nothing but a headache to keep up with ansible's idea of bumping
python every few months. Let's drop it entirely.
*
*
*
[y/n]

Drop python-netaddr dependency

---

frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/widget/renderer/RxTxDropRenderer.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/widget/host/HostNetworkInterfaceBondedListViewItem.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/widget/host/HostNetworkInterfaceListViewItem.java

Bug-Url: http://bugzilla.redhat.com/2180230
Change-Id: Iee6fa946f52481091a431a6ef0f173d74f9e37f2
*
*
*
[y/n]

webadmin: avoid NPE on null rx, tx drops

---

ovirt-engine.spec.in

Installing on a clean system with Italian locale, engine-setup fails with:
```console
[ INFO  ] Initializing PostgreSQL
[ INFO  ] Creating PostgreSQL 'engine' database
[ ERROR ] Failed to execute stage 'Misc configuration': ERRORE:  nome locale non valido "en_US.UTF-8"
[ INFO  ] DNF Performing DNF transaction rollback
[ INFO  ] DNF Repository copr:copr.fedorainfracloud.org:ovirt:ovirt-master-snapshot is listed more than once in the configuration
[ INFO  ] Stage: Clean up
Log file is located at /var/log/ovirt-engine/setup/ovirt-engine-setup-20230420105508-xx23f2.log
[ INFO  ] Generating answer file '/var/lib/ovirt-engine/setup/answers/20230420105553-setup.conf'
[ INFO  ] Stage: Pre-termination
[ INFO  ] Stage: Termination
[ ERROR ] Execution of setup failed
```
Requiring glibc-langpack-en …

Add glibc-langpack-en requirement

---

packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/db/schema.py

fixes issue  #841
This PR makes the database check succeed also when some object is not owned by the user, but the user is member of some role which owns the object.
The `pg_catalog.pg_has_role` function is available since postgres 8.1 (released in 2005).
The argument `'usage'` means that the user does not need to explicitly switch to the owner role using `SET ROLE`, which may be necessary with the alternative `'member'`.

ovirt-engine-setup database checks: being member of the database owner is also ok

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/utils/VdsCommandsHelper.java
build/ansible-check.sh

When picking a host for transfer-image job, we filter hosts that are UP and then process the data they reported on storage domains without checking whether the host actually reported this data. It can happen that hosts are UP and still have not reported data on storage domains, in which case the data is null, resulting in an NPE in the transfer-image flow.
This patch changes the predicate that is used to filter hosts for transfer-image, adding a null-check to avoid that NPE.
Bug-Url: https://bugzilla.redhat.com/2203132

Fix NPE when picking host for transfer-image

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/pool/SyncDirectLunsCommand.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/pool/SyncDirectLunsCommandTest.java

This patch fixes an NPE when running an unplugged disk's refreshlun command.
In case of refreshing an unplugged disk, the engine throws a NullPointerException. Example: [npe.txt](https://github.com/oVirt/ovirt-engine/files/11516191/npe.txt)
y

core:  Avoid NPE on refreshlun call without plugged VMs

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/pool/SyncDirectLunsCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/utils/VdsCommandsHelper.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/pool/SyncDirectLunsCommandTest.java

Backport NPE fixes

---

.github/workflows/build.yml
build/ansible-check.sh

* Enable ansible-lint execution
* Use the latest ansible-lint 6.y version
Fixes: https://github.com/oVirt/ovirt-engine/issues/851

Fix ansible-lint issues

---

backend/manager/tools/src/main/java/org/ovirt/engine/core/notifier/transport/smtp/EventMessageContent.java
backend/manager/tools/src/main/java/org/ovirt/engine/core/notifier/transport/smtp/LocalizedMessageHelper.java
backend/manager/tools/src/main/java/org/ovirt/engine/core/notifier/transport/smtp/MessageBody.java
backend/manager/tools/src/main/java/org/ovirt/engine/core/notifier/transport/smtp/MessageHelper.java
backend/manager/tools/src/main/java/org/ovirt/engine/core/notifier/transport/smtp/Smtp.java
backend/manager/tools/src/main/java/org/ovirt/engine/core/notifier/transport/smtp/SmtpMessageMerger.java
backend/manager/tools/src/main/resources/smtp-messages.properties
backend/manager/tools/src/main/resources/smtp-messages_ru.properties
backend/manager/tools/src/test/java/org/ovirt/engine/core/notifier/transport/smtp/LocalizedMessageHelperTest.java
backend/manager/tools/src/test/java/org/ovirt/engine/core/notifier/transport/smtp/SmtpMessageMergerTest.java
backend/manager/tools/src/test/java/org/ovirt/engine/core/notifier/transport/smtp/SmtpTest.java
packaging/services/ovirt-engine-notifier/ovirt-engine-notifier.conf.in

Hi, I would like to introduce couple email notification enhancements.
**ovirt-engine** has a separate service **ovirt-engine-notifier**. This service monitors events at the audit_log table and sends the notifications to different recipients (**amqp**, **snmp**, and **smtp**).
We are mostly interested in email notifications about engine backup events (**ENGINE_BACKUP_STARTED, ENGINE_BACKUP_FAILED, ENGINE_BACKUP_COMPLETED**).
_So, first_, when the **engine-backup.sh** script notifies **ovirt-engine** it sends multiple events in a row for each backup scope (**files, db, dwhdb, cinderlib, grafanadb**). Finally, If you start one backup then email recipients would receive 10 email messages (5 messages (one per scope item) about the backup started and 5 (one per scope item) messages about the …

Notification emails merging and localization

---

backend/manager/modules/services/src/main/webapp/novnc-main.jsp

noVNC dropped support for IE in commit
https://github.com/novnc/noVNC/commit/890cff921d78835762fbdcfef862571c52cb3035 As a result, the promise.js file was removed, and should not be referenced anymore from our code.
EL8 and EL9 already ship without promise.js file.

noVNC: don't use removed files

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/CloneVmNoCollapseCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/CloneImageGroupVolumesStructureCommand.java

Base volumes can be of QCOW format and preallocated type when the disk is set with incremental-backup enabled. When moving disks, we now propagate the incremental-backup settings forward to CreateVolume so it will keep these volumes preallocated on the destination storage domain.
Bug-Url: https://bugzilla.redhat.com/2211608

Do not change qcow+preallocated volumes when moving disks

---

packaging/ansible-runner-service-project/project/roles/ovirt-ova-pack/files/pack_ova.py

The size of the entry in the tar file for the OVF should match the length of the encoded ovf, otherwise the OVF parsing fails in case the encoded OVF is longer.

Fix creation of ova with encoded ovf

---

packaging/bin/pki-enroll-request.sh

* pki-enroll-request.sh checks if the CA file is stored on a local filesystem. However, the 'df' command output depends on the local system language, thus output may vary. With this patch LANG=C is forced just before the 'df' command is run.
Yes.

Force LC_ALL=C before running df -l command on pki-enroll-request

---

packaging/setup/ovirt_engine_setup/engine/constants.py
packaging/setup/ovirt_engine_setup/engine_common/keycloak_utils.py

with a single function, for now, keycloak_env_from_engine_conf.
Change-Id: I8d03c2ce9ec8fdad8afd796317ff1e69ea55ecbe

packaging: setup: Add keycloak_utils

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/GetUnregisteredDiskQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/GetUnregisteredDisksQuery.java

In a scenario where we managed to list the images on the storage, but failed to read get their information from vdsm, we will end up with engine assuming the OVF_STOREs are missing.
Instead this patch treats a failure to retrieve the infromation as a failure to force the user to retry.
Bug-Url: https://bugzilla.redhat.com/2244641

core: Fail when getVolumeInfo fails during OVF read

---

ovirt-engine.spec.in

Building on CBS for el9 failed because of maven 3.8 being selected instead of maven 3.6.
CBS EL9 builds for tags virt9s-ovirt-45* have set the value of block_maven_38 macro to 1 by default, but other build platforms are not affected by this.
See also: https://bugzilla.redhat.com/show_bug.cgi?id=2128991
y

spec: fix el9 build on CBS

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/GetUnregisteredDiskQuery.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/GetUnregisteredDisksQuery.java

In a scenario where we managed to list the images on the storage, but failed to read get their information from vdsm, we will end up with engine assuming the OVF_STOREs are missing.
Instead this patch treats a failure to retrieve the infromation as a failure to force the user to retry.
Bug-Url: https://bugzilla.redhat.com/2244641

backport: core: Fail when getVolumeInfo fails during OVF read

---

packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-kernel/tasks/main.yml

Remove unneeded quotes when running grubby to update
kernel cmdline.
Fixes: #775
Signed-off-by: Miguel Martín <mmartinv@redhat.com>

fix: remove unneeded quotes when updating kernel cmdline

---

packaging/bin/engine-backup.sh.in

Restore proper selinux context for /var/lib/grafana/grafana.db when
restoring from backup created by engine-backup.

Restore grafana.db selinux context after engine-restore

---

frontend/webadmin/modules/frontend/src/main/java/org/ovirt/engine/ui/frontend/server/gwt/GenericApiGWTServiceImpl.java

CreateUserSesssion should be executed only as a part of login flow, so
explicitly disable execution from GWT code.

Disable execution of CreateUserSession from GWT code

---

frontend/webadmin/modules/frontend/src/main/java/org/ovirt/engine/ui/frontend/server/gwt/GenericApiGWTServiceImpl.java

CreateUserSesssion should be executed only as a part of login flow, so
explicitly disable execution from GWT code.

backport: Disable execution of CreateUserSession from GWT code

---

packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/network/ovirtproviderovn.py

The keytool command before this _set_file_permissions is not executed in DEVELOPER_MODE.
If we execute the chmod, it fails with:
Failed to execute stage 'Misc configuration': [Errno 2] No such file or directory: '/home/xxx/xxx/var/lib/ovirt-engine/external_truststore' as the file was not created.

Skip chmod of ENGINE_EXTERNAL_PROVIDERS_TRUST_STORE in DEVELOPER_MODE

---

packaging/bin/pki-create-ca.sh

* The engine-setup was giving issues when generating the .pem files, because the directory was not changed early enough. This has been fixed
Yes
Co-authored-by: Jean-Louis Dupond [jean-louis@dupond.be](mailto:jean-louis@dupond.be)
Signed-off-by: Brooklyn Dewolf [contact@brooklyn.gent](mailto:contact@brooklyn.gent)

Fix CA generation as non-root user due to .rnd error

---

packaging/dbscripts/dbfunc-common.sh
packaging/dbscripts/dbfunc-custom.sh

There were some remained parts after materialized views functionality deletion. Comments and if-blocks that don't mean anything now. Initial deletion commit hash: fa5ead39d36cb999460f853d4573a36dba8ec8b0
[y/n] y

db: cleanup: Remove crumbs after materialized views deletion

---

backend/manager/modules/enginesso/src/main/java/org/ovirt/engine/core/sso/service/ExternalOIDCService.java

Before the keycloak v22 it sends empty array as group claim when user not a member of any group. After v22 it not put this claim at all.
Look discussion: https://github.com/keycloak/keycloak/issues/22340
y

Handle situation when empty groups not come from the keycloak

---

backend/manager/modules/enginesso/src/main/java/org/ovirt/engine/core/sso/service/ExternalOIDCService.java

This is linked with this change for V19: https://www.keycloak.org/docs/latest/upgrading/index.html#userinfo-endpoint-changes
Now for request user-info endpoint we need request token with 'openid' scope (this is required scope by the standard)
y

engine: add scope 'openid' for compatibility with new versions of the keycloak

---

packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/network/ovirtproviderovn.py

This fixes engine-setup error:
[ ERROR ] Failed to execute stage 'Misc configuration': 'OVESETUP_OVN/ovirtProviderOvnSecret'
Since commit 978c90e we save the ovirtProviderOvnSecret value in the setup file.
But if this value is not there, but ovirtProviderOvn is True, the engine-setup fails.
So if we can't find the value in the config, a new password is generated.
[y]

packaging: fix error when enabling KeyCloak

---

.github/workflows/build.yml

* Dropping automation on el8 stream as centos stream 8 reached EOL.
y

automation: drop el8 after centos stream 8 eol

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/backup/HybridBackupCommand.java

Fixes an issue that originates from https://github.com/oVirt/ovirt-engine/commit/ed023e5e0a000029b4d7e50b03fdbb3fd9a773bd
* Fixes the following error when creating an incremental backup:
`
ERROR [org.ovirt.engine.core.bll.storage.backup.HybridBackupCommand] (default task-1) [full_cold_vm_backup] Command 'org.ovirt.engine.core.bll.storage.backup.HybridBackupCommand' failed: CallableStatementCallback; SQL [{call insertvmbackup(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}]; ERROR: duplicate key value violates unique constraint "vm_backups_pkey"
Detail: Key (backup_id)=(1733241d-4a0b-4205-9e52-5383eb7a82f2) already exists.
`
y

engine: Fix duplicate VM backup entry error when creating incremental backup

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferImageStatusCommand.java
backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/storage/disk/image/TransferImageStatusCommandTest.java

There is some situations when storageDomainId is not come with parameters (image upload cancel and pause operations) for TransferImageStatusCommand. For this operations checked CREATE_DISK permission on SYSTEM_OBJECT (i.e. system-wide). Problem starts when we give permissions for user only on concrete storage domain object (not system-wide). Then permission check failed for operations without storage domain id info in parameters. Here I just add check permission for disk before other objects.
y

engine: Check concrete disk permissions firstly on TransferImageStatus

---

packaging/ansible-runner-service-project/project/roles/ovirt-provider-ovn-driver/tasks/configure.yml

Signed-off-by: ShubhaOracle <Shubha.kulkarni@oracle.com>
Fixes issue # Host addition to new cluster failed
- Changes introduced with this PR:
When adding a host to a new cluster, host addition failed due the check for ovn_central failed. Added the fix to check if variable ovn_central is defined and is not None and empty 
- Problem Description
Steps:
1. Create a new data center with default settings
2. Create a new cluster with default settings and the the new data center. CPU type is "Auto Detect"
3. Install RPM on a fresh installed server
4. Add the the server to the new cluster
Symptom: The host installation failed. The cluster CPU Type is blank. If activating the host a few times, the host is in non-operational status but the cluster CPU type will be changed to "Secure Intel Skylake …

Adding host to a new cluster failed

---

packaging/ansible-runner-service-project/project/ovirt-host-upgrade.yml

Fixes issue of not being able to upgrade packages on nodes via ovirt
* fix ovirt Ansible playbook to work with newer ansible-core releases after 2023-05-16
* taken from [Marco Fais](https://lists.ovirt.org/archives/users/110553723741550915061952827377007637131/) https://lists.ovirt.org/archives/list/users@ovirt.org/message/3HABK6CMJOGRLKLZSMXEZPSNPM473LVS/
[y]

replace deprecated Ansible include with import_tasks

---

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/storage/UploadImageModel.java

Signed-off-by: Stepan Ermakov <sermakov@orionsoft.ru>
This PR fixes the following issue: incorrect Data Center is displayed when uploading a disk image from "Storage Domain Disks" UI.
**Steps to reproduce:**
1. Create a Storage Domain at a non-Default Data Center.
2. Open the Storage -> Domains -> [The created Storage Domain] -> Disks page.
3. Select the Upload -> Start menu item. The "Upload image" dialog is displayed.
**Expected behavior:**
The Data Center field is disabled and displays the name of the non-Default Data Center.
**Current behavior:**
The Data Center field is disabled and displays the name of the Default Data Center.
Fixed in the following way: when "Upload image" dialog is displayed then query the Storage Domain details with information about its Data Center and select …

Issue: Incorrect Data Center for the "Upload Image" dialog

---

packaging/dbscripts/vms_sp.sql

Issue:
When VM emulator is changed to Q35 Chipset with UEFI SecureBoot from Q35 Chipset with UEFI, the NVRAM file needs to be rewritten.
Fix:
On VM update remove the previous NVRAM file.
Signed-off-by: Saksham Srivastava saksham.sa.srivastava@oracle.com

"secure boot" not getting enabled for Chipset/Firmware Type "Q35 Chipset with UEFI SecureBoot"

---

packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/core/misc.py

When using an answer file that contains:
QUESTION/1/OVESETUP_ENGINE_ENABLE=str:yes
The CoreEnv.ENABLE was not set to True if fqdn's didn't match and it was not a new database.
But as we explicitly want to enable the engine according to the answer file, we must enable it.
[y]

packaging: enable engine when it was enabled in answer file

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/MoveOrCopyDiskCommand.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/lsm/LiveMigrateDiskCommand.java

When doing a LiveStorageMigration, the code checked if the disk/image would fit not only on the destination, but also on the source. This because theoretically the snapshot image can grow until the disksize.
But this means that we needed to live migrate a 1TB disk, also at least 1TB of free space on the source domain.
This is quite useless, and causes problemns to move disks from for example an already overloaded source domain.
As this check is neither being done when creating a simple snapshot, just drop the check on the source domain.
[y]

bll/storage: don't check source domain space on lsm

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/AddDiskCommand.java

* When a standalone disk is made, don't try to release locks on VM, because there are none
* Before this change the creation of a standalone disk always generated a warning because of this.
[y]

core: only try to unlock vm if vm present

---

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/popup/storage/RegisterEntityInfoPanel.java

Signed-off-by: ShubhaOracle <Shubha.kulkarni@oracle.com>
Intermittent UI exception while opening the Import Virtual Machine(s) pop-up
```
Stack Trace when error happens:
2023-07-17 11:11:12,436-06 ERROR [org.ovirt.engine.ui.frontend.server.gwt.OvirtRemoteLoggingService] (default task-43) [] Uncaught exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : a is null
at java.math.Conversion.toDecimalScaledString(Conversion.java:175)
at org.ovirt.engine.ui.webadmin.section.main.view.popup.storage.RegisterEntityInfoPanel18.18.18.getRawValue(RegisterEntityInfoPanel.java:314)
at org.ovirt.engine.ui.webadmin.section.main.view.popup.storage.RegisterEntityInfoPanel$18.getRawValue(RegisterEntityInfoPanel.java:314)
```
* Add checks for null values

Issue: Intermittent UI exception while opening the Import Virtual Machine(s) pop-up

---

pom.xml

Just small update for jsass dependency.
It has some prebuilded binaries within.
New version brings some small bug fixes and binaries for arm cpu's.
This is the only one thing that broke builds (and local work) on arm-based apple computers.
yes

[engine] Update jsass to bring some fixes and possibility for build under arm macos

---

backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/SecretValue.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/widget/uicommon/vm/VmSnapshotInfoPanel.java

This PR fixes the https://github.com/oVirt/ovirt-engine/issues/900 issue.
Since the SecretValue structure is used in GWT, it should implement Serializable interface. Also couple null checks were added to avoid NPE in the scenario explained in the #900 issue.
Yes

fix: SerializationException: Type 'org.ovirt.engine.core.common.utils.SecretValue' was not included in the set of types... #900 

---

build-tools-root/ovirt-findbugs-filters/pom.xml
pom.xml

Set a parent in ovirt-findbugs-filters to make sure we pull same dependencies there as in the root project.
Move ovirt-findbugs-filters to a plugin to avoid a cyclic dependency when building.
Pin a version for maven-install-plugin.
This all to make sure we build using the same dependencies on all OS'es. We need this for example on COPR to have correct dependencies included in ovirt-engine-build-dependencies, as the srpm is build there on FC41 which has different plugin versions in its Super POM.
[y]

pom: align dependencies when using different maven versions

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/UpdateDiskCommand.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/job/StepEnum.java
backend/manager/modules/dal/src/main/resources/bundles/ExecutionMessages.properties

- Implemented messages for step information when extending a disk.
- Added default part to switch statements in UpdateDiskCommand to solve warnings in code editor regarding certain disk storage types not being included in the switch statement.
- Removed amendImageGroupVolumesCommandParameters function due to being unused method.
[y]

core: fix extend image message when extending disks

---

backend/manager/modules/restapi/interface/definition/pom.xml
pom.xml

The version of jaxb2-maven-plugin was incorrectly referenced in the main pom.xml and another version was used in the interface definition pom. Align this to use same version and fix version reference.
[y]

pom: fix jaxb2-maven-plugin version

---

pom.xml

Add the OSS RH Snapshots repository.
This way we can build ovirt-engine against SNAPSHOT builds of org.ovirt.*
[y]

pom: add ossrh snapshots repository

---

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/EngineBackupAwarenessManager.java
backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/aaa/GetLastEngineBackupQuery.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/EngineBackupScope.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/queries/GetLastEngineBackupParameters.java
backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/queries/QueryType.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendApiResource.java
backend/manager/modules/restapi/jaxrs/src/test/java/org/ovirt/engine/api/restapi/resource/BackendApiResourceTest.java
frontend/webadmin/modules/gwt-common/src/main/resources/org/ovirt/engine/core/Common.gwt.xml
pom.xml

* Exposes the dates of the last succesfull backups to the api, needs https://github.com/oVirt/ovirt-engine-api-model/pull/110 to function.
[y]

Last backup api extension

---

backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/businessentities/storage/LUNs.java
backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/StorageLogicalUnitMapper.java

* A new field has been added <active_paths> to the /ovirt-engine/api/hosts/xxxx/storage endpoint that represents the multipaths that are NOT faulty as an integer value
* needs https://github.com/oVirt/ovirt-engine-api-model/pull/113 to function
[y]

Added iSCSI multipath status to the API

---

backend/manager/modules/common/pom.xml
backend/manager/modules/compat/pom.xml
frontend/webadmin/modules/gwt-common/pom.xml
frontend/webadmin/modules/gwt-extension/pom.xml
frontend/webadmin/modules/pom.xml
pom.xml

It was made for GWT that didn't support newer than java 8 versions. From some time it starts to support java 11 (current version already can compile on that)
Removed some parts from maven settings that connected with java-8
[y/n] -> yes

core: remove the rest build parts for java 8

---

backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/VmDaoImpl.java

When the is a NvramData row in the db, but without data, the getExternalData() call fails with a NPE:
ERROR [org.ovirt.engine.core.bll.HasNvramDataQuery] (default task-179) [4e047baa-c81c-4673-9cd2-6984d0e7477f] Exception: java.lang.NullPointerException
at java.base/java.lang.String.<init>(String.java:236)
at org.ovirt.engine.core.dal//org.ovirt.engine.core.dao.VmDaoImpl.lambda$getExternalData$6(VmDaoImpl.java:416)
This because 'new String(null)' gives this NPE.
As we don't need to call 'new' here, just remove it to fix the issue.
*
*
*
[y]

core: fix NPE when NvramData is empty

---

packaging/dbscripts/audit_log_sp.sql

The `customId` field in `org.ovirt.engine.core.common.businessentities.AuditLog` entity is not persisted when saving an audit log entry via `org.ovirt.engine.core.dao.AuditLogDao`. This is due to a missing `custom_id` parameter in the `InsertAuditLog` stored procedure.
* Add missing `custom_id` parameter in the `InsertAuditLog` stored procedure.
Yes

Add missing custom_id in audit_log_sp.sql

---

frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/widget/uicommon/vm/BaseVmDiskListModelTable.java

* When looking up information about a vm, the disk id was not present in the table with information about it's disks, this patch add's it as an optional column.
[y]

core: added disk id as optional column on subtab disks for VM's

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmResource.java

Add the optional `attach_wgt` flag to the vm start endpoint. This will auto attach the virtio-win iso (if it is available) to the vm at boot time. The actual logic needed to attach the iso was implemented earlier for usage in the GUI.
Needs: https://github.com/oVirt/ovirt-engine-api-model/pull/116
y

restapi: add attach_wgt flag to vm start endpoint

---

frontend/webadmin/modules/frontend/pom.xml
frontend/webadmin/modules/gwt-aop/pom.xml
frontend/webadmin/modules/gwt-common/pom.xml
frontend/webadmin/modules/gwt-extension/pom.xml
frontend/webadmin/modules/pom.xml
frontend/webadmin/modules/uicommonweb/pom.xml
frontend/webadmin/modules/uicompat/pom.xml
frontend/webadmin/modules/webadmin/pom.xml
pom.xml

In new releases there are small fixes and possibility to build it with newer versions of java (up to 21).
With GWT update I aligned maven configuration to build all modules with java-11. 
It builded successfully on my machine.
I prepared small setup for testing (one host and one nfs storage domain).
And looked by hands on two browsers (firefox and chrome).
All things looks good for me.
[y/n] y

core: update GWT to the newer version

---

.github/workflows/ost.yaml

This is now needed to run ost, otherwise you get the error:
Error calling workflow 'oVirt/ovirt-system-tests/.github/workflows/ost.yaml@master'.
The workflow is requesting 'pull-requests: write',
but is only allowed 'pull-requests: none'.
[y]

Add pull-request write access to ost-trigger

---

frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/CommonApplicationConstants.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/section/main/presenter/OptionsPopupPresenterWidget.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/utils/ConsoleOptionsFrontendPersisterImpl.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/view/popup/OptionsPopupView.java
frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/view/popup/OptionsPopupView.ui.xml
frontend/webadmin/modules/gwt-common/src/main/resources/org/ovirt/engine/ui/common/CommonApplicationConstants.properties
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/ConsoleOptionsFrontendPersister.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/options/EditOptionsModel.java
frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/options/OptionsModel.java

* Introduces option to change vnc console invocation protocol (Native or NoVnc) during runtime on a user basis for all vm's. 
* This setting is saved in the local storage, where individual selection of console type for a VM is also saved.
* When default is selected it falls back to the VNC type set in the config values. 
[y]

core: added option for user to decide preference of vnc console invocation

---

CONTRIBUTING.adoc
config/engine-commit-template.txt

Add a CONTRIBUTING.adoc file with some guidelines on how to format commit (messages).
This to have some guidelines for new contributors to the project.

docs: add a CONTRIBUTING.adoc

---

packaging/conf/osinfo-defaults.properties

* added RHEL10 to osinfo list. All config is inherited from rhel_8x64

add RHEL10 to osinfo list

---

packaging/ansible-runner-service-project/project/ovirt-host-reconfigure-ovn.yml

KVM host upgrade marked as failed because ansible task "[Reconfigure OVN for oVirt]" fails
*Fix ovn_central validation for None/Empty. Fix the openvswitch version.
Yes

Fix ovn validations when upgrading host

---

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/ApplicationConstants.java
frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/popup/provider/ProviderPopupView.ui.xml
frontend/webadmin/modules/webadmin/src/main/resources/org/ovirt/engine/ui/webadmin/ApplicationConstants.properties

Fixes issue https://github.com/oVirt/ovirt-engine/issues/446
* Adapted the protocol label to use a constant instead of a hard coded string.
[y]

webadmin: internationalize forgotten hard coded string

---

ovirt-engine.spec.in

Add a BuildRequires to maven-local-openjdk21.
This can replace dependency on javapackages-tools as the maven-local-openjdk21 has it as requirement.
[y]

spec: add buildrequirement on maven-local-openjdk21

---

packaging/bin/java-home
packaging/pythonlib/ovirt_engine/java.py

- Remove support for multiple modules since reports has been archived
- No more hard-coded paths, if paths change in the future things should keep on working
- Allow any JRE version >= 11 so that the default java versions on both CentOS 9 and 10+ work.
- Previous vars meant to override JRE have been kept intact.
y

core: fix java-home detection

---

backend/manager/dependencies/common/pom.xml
backend/manager/dependencies/common/src/main/modules/com/ongres/scram/client/main/module.xml
backend/manager/dependencies/common/src/main/modules/com/ongres/scram/common/main/module.xml
backend/manager/dependencies/common/src/main/modules/com/ongres/stringprep/saslprep/main/module.xml
backend/manager/dependencies/common/src/main/modules/com/ongres/stringprep/stringprep/main/module.xml
ovirt-engine.spec.in
pom.xml

Adding stringprep/saslprep and scram(client/common) as dependencies in the pom.
This is needed to fix local builds. Otherwise the jars for those modules are missing.
Next to that also rename stringprep and saslprep with the stringprep prefix as this is more clear they are in the same groupId.
[y]

core: add stringprep/scram to dependency

---

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmResource.java
backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/util/DisplayHelper.java
backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/DisplayMapper.java
backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/InstanceTypeMapper.java
backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/TemplateMapper.java
backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/VmBaseMapper.java
backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/VmMapper.java
backend/manager/modules/restapi/types/src/test/java/org/ovirt/engine/api/restapi/types/VmMapperTest.java

* When pulling info for a vm, template or instance type through the API return a video_type in the console info together with the graphic console as the type. Ability to alter the video device attached to a vm through the PUT api call. Saves this update as a configuration for the next run of the VM if it is in the up state.
* Needs https://github.com/oVirt/ovirt-engine-api-model/pull/117 implemented in api model to properly function.
[y]

core: added ability to alter video device through API

---

ovirt-engine.spec.in
packaging/bin/engine-backup.sh.in
packaging/setup/ovirt_engine_setup/engine_common/database.py
packaging/setup/plugins/ovirt-engine-remove/base/core/misc.py

- Add python3-looseversion dependency. This is a drop-in replacement for the
deprecated distutils.version.LooseVersion. We prefer looseversion above
packaging.version.Version. The latter is meant to compare python package versions that
adhere to PEP-440. We are not strictly comparing python packages, so if we use
the strict "packaging" implementation we could encounter unexpected errors.
- Change the imports from distutils.version to loosversion where needed.
y

remove usage of deprecated Looseversion 

---

frontend/brands/ovirt-brand/src/main/resources/bundled/patternfly-next/patternfly-no-reset.css

* Due to badly formed css in the branding files, the sending of the altered file resulted in a broken pipe.
[y]

webadmin: fix broken pipe on branding css file
