.github/CODEOWNERS
I've always reviewed frontend patches only, other
patches are not in my area of expertise.
Signed-off-by: Lucia Jelinkova <ljelinko@redhat.com>
=> github: moving myself from default to frontend owners

frontend/brands/ovirt-brand/src/main/sass/_dialogs.css
Bug-Url: https://bugzilla.redhat.com/1846340
=> webadmin: fix extra white areas in tabbed dialogs

.automation/build-rpm.sh, .automation/build-srpm.sh, .github/workflows/build.yml, pom.xml
- Build RPMs using GH actions
- Use ovirt/upload-rpms-action for RPM artifacts
=> Backport RPM build to ovirt-engine-4.4

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/CopyDataCommand.java, backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/CreateVolumeContainerCommand.java, backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/CopyDataCommandParameters.java, backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/CreateVolumeContainerCommandParameters.java, backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/vdscommands/CopyVolumeDataVDSCommandParameters.java, backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/vdscommands/CreateVolumeVDSCommandParameters.java, backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/irsbroker/CreateVolumeVDSCommand.java, backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/irsbroker/IIrsServer.java, backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/jsonrpc/JsonRpcIIrsServer.java, backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/jsonrpc/JsonRpcVdsServer.java, backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/CopyVolumeDataVDSCommand.java, backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/IVdsServer.java, backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/NullVdsServer.java
This is preliminary work required for converting disks, as the image created would be created illegal. This PR adds flags to:
* Indicate a volume is going to be created illegal
* Indicate copying data will be done to an illegal volume
=> Support illegal creating and copying illegal volumes

packaging/setup/plugins/ovirt-engine-common/ovirt-engine-common/system/fapolicyd.py, packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/config/__init__.py, packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/config/jboss_fapolicyd.py
- Style fixes for fapolicyd setup
- Skip fapolicyd setup for dev environment: fix
=> Fix fapolicyd setup for dev environment

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/TransferDiskImageCommand.java
Currently when a transfer will fail stopImageTransferSession as part of
handleFinalizingSuccess it will finish successfully, leaving garbage
behind and the image will remain locked.
This patch is a partial revert of c54d500, enabling cleanup retries if
stopping the transfer session fails.
Bug-Url: https://bugzilla.redhat.com/2057445
=> core: fix retry for transfer image stopImageTransferSession failure

packaging/man/man8/engine-cleanup.8, packaging/man/man8/engine-setup.8, packaging/setup/bin/ovirt-engine-remove, packaging/setup/bin/ovirt-engine-rename, packaging/setup/bin/ovirt-engine-setup, packaging/setup/ovirt_engine_setup/constants.py, packaging/setup/plugins/ovirt-engine-common/base/core/__init__.py, packaging/setup/plugins/ovirt-engine-common/base/core/show_doc_text.py, packaging/setup/plugins/ovirt-engine-common/vmconsole_proxy_helper/core.py
Bug-Url: https://bugzilla.redhat.com/1700460
Change-Id: Ia92bda4e623db242f383fd8e44158df549eb1e2d
=> packaging: setup: Add answer file documentation

packaging/dbscripts/create_dwh_views.sql
Update read/write_ops_per_second to read_write_ops_total_count
Bug-Url: https://bugzilla.redhat.com/2010903
Signed-off-by: Aviv Litman <alitman@redhat.com>
=> db: update read/write ops dwh columns names

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ConvertDiskCommand.java
We neet to check if the getVolumeInfo checks succeeded or not and consider them before proceeding to remove the disk. Otherwise the source disk will be removed in the negative flow.
=> core: fix error handling when switching image

.automation/build-rpm.sh
=> Enable unit tests during RPM build

packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/config/aaajdbc.py, packaging/setup/plugins/ovirt-engine-setup/ovirt-engine/upgrade/auth_url_validation.py
Remove unused variables from .format()
=> packaging: fix flake8 issues

backend/manager/modules/searchbackend/src/test/java/org/ovirt/engine/core/searchbackend/SyntaxCheckerTest.java
Fixing faling test.
Signed-0ff-by: Eli Mesika <emesika@redhat.com>
Bug-Url: https://bugzilla.redhat.com/2051462
=> fix BZ 2051462 tests

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendHostCpuUnitsResource.java, backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/HostMapper.java
Add implementation for retrieving the list of the host's physical CPUs with the current pinning status.
=> restapi: add host cpu units

frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/storage/UploadImageModel.java
When uploading a disk from Storage > Domain > select domain > Disks > Upload, after selecting a
host different from the first one on the list, the selection immediately
resets back to the first host suggested.
By initializing the unchangeable data center and storage domain once
the model loads for the first time, we avoid the resetting.
Bug-Url: https://bugzilla.redhat.com/2041544
=> webadmin: avoid resetting host selection on upload disk

pom.xml
Changes from 4.5.4:
backup: introduce the use_active flag
Add upgrade progress tracking for Clusters
https://bugzilla.redhat.com/2040474
Added Display.disconnectActionDelay
https://bugzilla.redhat.com/1944834
Signed-off-by: Ori Liel <oliel@redhat.com>
=> bump model version to 4.5.5

backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/TemplateMapper.java, backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/VmBaseMapper.java, backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/VmMapper.java, backend/manager/modules/restapi/types/src/test/java/org/ovirt/engine/api/restapi/types/TemplateMapperTest.java, backend/manager/modules/restapi/types/src/test/java/org/ovirt/engine/api/restapi/types/VmMapperTest.java
Added mapping of Display.disconnectActionDelay from REST API to
VmBase.consoleDisconnectActionDelay.
Bug-Url: https://bugzilla.redhat.com/2055666
=> Added mapping of Display.disconnectActionDelay

bump_release.sh
adjust copr config for release / nightly
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
=> bump_release: adjust copr config

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/MigrateVmCommand.java, backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommand.java, backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/RunVmCommandBase.java, backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/VmHandler.java, backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/utils/NumaPinningHelper.java, backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/vdscommands/MigrateVDSCommandParameters.java, backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/VmDynamicDao.java, backend/manager/modules/dal/src/main/java/org/ovirt/engine/core/dao/VmDynamicDaoImpl.java, backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/MigrateBrokerVDSCommand.java, backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/vdsbroker/VdsProperties.java, packaging/dbscripts/vms_sp.sql
Send the new numa pinning string during the migration so that the pinning is changed on the destination host.
=> Add migration support for dedicated cpus with numa

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/widget/host/HostNetworkInterfaceListViewItem.java
Change-Id: I45f21b8778d4cb9c2c6db3714edfb562503bc2f3
Change-Id: I8c05007ebcaf0bb049208ec25c3242521c1458c8
=> webadmin: prevent NPE in host interface list

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelper.java, backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/bll/scheduling/utils/VdsCpuUnitPinningHelperTest.java
Fixed the logic when looping over virtual NUMA that can be within
physical NUMA.
=> Follow up fix for dedicate numa

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/storage/disk/image/ConvertDiskCommand.java
When calling DestroyImageCommand upon failure we need to remove the
references to the parent command, otherwise CoCo will try to notify it
about its child completion, but the parent command will be already gone
at this point and this will lead to an NPE.
By unsetting the parent command references, CoCo will have no one to
notify and there is no need to as this command runs in detached context.
Bug-Url: https://bugzilla.redhat.com/2069670
Depends on: https://github.com/oVirt/ovirt-engine/pull/203
=> core: unset references for parent command when cleaning up

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/UpdateVmVersionCommand.java
This patch fixes an NPE when running UpdateVmVersion.
Change-Id: I19390c937d79fc7244b0a94bf055f2fbcc2249dd
=> core: fix NPE in update vm version

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleCommandConfig.java, backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleExecutor.java
Reverts oVirt/ovirt-engine#227
=> Revert "Use ansible-runner project-dir and code cleanup"

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmBackupsResource.java
backport https://github.com/oVirt/ovirt-engine/pull/268
=> restapi: restore suggestedParent

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmBackupResource.java, backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendVmBackupsResource.java
Backport of https://github.com/oVirt/ovirt-engine/pull/303
=> Backport: revert snapshot link

ovirt-engine.spec.in
This reverts commit dc6d66e6c76f4ce43a64f644012a1f0c1a02d3c6.
=> Revert "Disable default keycloak integration"

.copr/Makefile
=> Add debug command to investigate COPR build failures

.copr/Makefile
=> Fix marking repo dir for COPR as safe

.copr/Makefile
=> Fix marking repo dir for COPR as safe 2

.copr/Makefile
=> Fix marking repo dir for COPR as safe 3

.copr/Makefile
=> Fix marking repo dir for COPR as safe 5

.copr/Makefile
=> Optimize marking repo dir as safe for the COPR build

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmCommand.java, backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmCommandBase.java
When a VM with lease is exported, the ID of the storage domain where the
lease is located is saved in the OVF. When this VM is imported, the
lease is created by default on the same storage domain. But, if there is
no storage domain with such ID, the lease is not created at all.
This patch changes this behaviour. If there is no storage domain with
the same ID, the lease is created on another storage domain where it is
possible.
The logic moved to handle all VM import cases.
Change-Id: Id251aecb41e0cb1d7b0b1fee762436bca5cccc5b
Bug-Url: https://bugzilla.redhat.com/2023368
=> Default SD for imported VM with lease

backend/manager/modules/utils/src/main/java/org/ovirt/engine/core/utils/ovf/OvfReader.java
Code styling: uniting if statements for setting disk type and format.
=> core: code styling: uniting if statements

pom.xml
Bug-Url: https://bugzilla.redhat.com/1992141
=> Bump apache-commons-compress to 1.21

pom.xml
Bump to model 4.5.10
Following changes has been made since 4.5.7:
* Add parallel migration connections
https://bugzilla.redhat.com/2078500
* Introduce isolate threads CpuPinningPolicy
https://bugzilla.redhat.com/1782077
* Standardize links within documentaiton
Signed-off-by: Ori Liel <oliel@redhat.com>
=> Bump to model 4.5.10

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/host/HostUpgradeManager.java
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2096523
=> add ssh port to ansible command config vars on check for upgrade

README.adoc
Add to readme how to setup ansible-lint for engine
=> README: Add ansible-lint setup

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/exportimport/ImportVmFromExternalUrlCommand.java, frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/dataprovider/AsyncDataProvider.java, frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/storage/DisksAllocationModel.java, frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/ImportVmFromExportDomainModel.java, frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/ImportVmFromExternalSourceModel.java, frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/ImportVmFromOvaModel.java, frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/vms/NewDiskModel.java
=> Encapsulate logic that sets qcow for incremental backup

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/AnsibleCallback.java, backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerClient.java
Ansible: fix debug log for the events
=> Ansible: fix debug log for the events

packaging/ansible-runner-service-project/project/roles/ovirt-host-upgrade/tasks/main.yml
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2090670
=> Remove network-scripts-openvswitch 2.11 package before installing ovirt-host

backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendOperatingSystemResource.java, backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendOperatingSystemsResource.java, backend/manager/modules/restapi/types/src/main/java/org/ovirt/engine/api/restapi/types/TpmSupportMapper.java
Depends on: https://github.com/oVirt/ovirt-engine-api-model/pull/78
Reference-Url: https://github.com/oVirt/ovirt-web-ui/issues/1596
=> restapi: expose TPM support provided by the OS

.github/workflows/build.yml
Change-Id: I2a35a9d3fdd6b4f564ca7f9d9666c0ecf9847295
=> github: Fix checkout

.github/workflows/build.yml
=> Enable CI on ovirt-engine-4.5.2.z branch

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleCommandConfig.java, backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleExecutor.java
Upgrade Cluster role is run locally on engine, "host" is not defined.
Do not raise on that.
This reverts f7561f9d8a87271be7d6454e27325bd04178664f
=> backport #588

.github/workflows/build.yml
Change-Id: Ifa9104830ae6cddbc932cd786dc3a2fedd168dea
=> github: use ovirt/checkout-action

.copr/Makefile
Change-Id: Ib8e8deeca6ddbda02e3ba7dafef5b872d70d18b1
=> build: .copr/Makefile: Fix setting release_suffix

backend/manager/modules/dal/pom.xml, backend/manager/modules/uutils/pom.xml, ear/pom.xml, pom.xml
- Bump maven-dependencies-plugin to 3.3.0
- Bump dbunit to 2.7.3
- Bumpe maven-surefire-plugin to 3.0.0-M7
- Bump maven-ear-plugin to 3.2.0
- Bump maven plugin versions
=> dependencies and plugins versions

packaging/ansible-runner-service-project/project/ovirt-host-reconfigure-ovn.yml, packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-facts/tasks/host-os.yml, packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-kdump/tasks/main.yml, packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-misc/tasks/gluster.yml, packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vdsm/tasks/packages.yml, packaging/ansible-runner-service-project/project/roles/ovirt-host-upgrade/tasks/main.yml, packaging/ansible-runner-service-project/project/roles/ovirt-provider-ovn-driver/tasks/configure.yml
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2118672
=> Use rpm instead of auto in package_facts ansible module

pom.xml
Signed-off-by: Ori Liel <oliel@redhat.com>
=> bump model (4.5.12), metamodel (1.3.10)

ovirt-engine.spec.in
Limit GWT resources to pass the build on CBS
=> Limit GWT resources to pass the build on CBS

ovirt-engine.spec.in
=> Fix limiting GWT resources during RPM build

ovirt-engine.spec.in
=> backport: Fix limiting GWT resources during RPM build

ovirt-engine.spec.in
- Skip validation of build environment
- Increase GWT localWorkers to 2
=> fix cbs el9 build issue

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/tab/cluster/SubTabClusterVmView.java
Add CPU Count, CPU Usage, Defined Memory, Memory Usage, Network, IP address tabs in Compute | Cluster |Virtual Machines view,  according to issue #643
=> Add additional columns to Compute-Cluster-Virtual Machines view

ovirt-engine.spec.in, pom.xml
=> Bump apache-sshd to 2.9.2

ovirt-engine.spec.in
Related to https://github.com/oVirt/ovirt-ansible-collection/pull/632 and https://github.com/oVirt/ovirt-hosted-engine-setup/pull/70
=> Switch to ansible-core 2.13 on CS8

packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-ovn-certificates/tasks/main.yml, packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vdsm-certificates/tasks/main.yml, packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vdsm/tasks/configure.yml, packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vdsm/tasks/libvirt_presets_configure.yml, packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vdsm/tasks/main.yml, packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vnc-certificates/tasks/main.yml, packaging/ansible-runner-service-project/project/roles/ovirt-ova-extract/tasks/main.yml, packaging/ansible-runner-service-project/project/roles/ovirt-ova-pack/tasks/main.yml, packaging/ansible-runner-service-project/project/roles/ovirt-ova-query/tasks/main.yml, packaging/ansible-runner-service-project/project/roles/ovirt-provider-ovn-driver/tasks/configure.yml
Fixes wrong indentation in Ansible playbooks/roles, which is reported by ansible-lint as errors.
=> Fix wrong indentation in Ansible playbooks/roles 

ovirt-engine.spec.in, pom.xml
=> Bump postgresql-jdbc to 42.2.27

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/AnsibleRunnerCleanUpService.java
It doesn't  affect functionality of the fix for https://bugzilla.redhat.com/2151549 but it eases debugging significantly
=> backport: add debug logging to AnsibleRunnerCleanUpService

backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/bll/validator/AnsibleRunnerCleanUpService.java
- add debug logging to AnsibleRunnerCleanUpService
- add debug info
=> Artifacts cleanup descriptive debug additions

frontend/webadmin/modules/gwt-common/src/main/java/org/ovirt/engine/ui/common/widget/renderer/RxTxDropRenderer.java, frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/widget/host/HostNetworkInterfaceBondedListViewItem.java, frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/widget/host/HostNetworkInterfaceListViewItem.java
Bug-Url: http://bugzilla.redhat.com/2180230
Change-Id: Iee6fa946f52481091a431a6ef0f173d74f9e37f2
*
*
*
[y/n]
=> webadmin: avoid NPE on null rx, tx drops

i18n/pom.xml, pom.xml
- Upgrade snakeyaml to 1.33
- Bump jackson to 2.12.7
- Bump SpringFramework to 5.3.27
- Bump jackson-databind to 2.12.7.1
=> bump dependencies

.github/workflows/build.yml
=> Use latest version of github actions

.github/CODEOWNERS
* Adressing errors reported by https://github.com/oVirt/ovirt-engine/blob/master/.github/CODEOWNERS
y
=> CODEOWNERS: removed people who left the project

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/ApplicationConstants.java, frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/MainStorageView.java, frontend/webadmin/modules/webadmin/src/main/resources/org/ovirt/engine/ui/webadmin/ApplicationConstants.properties
* Added "Allocated Space" column in Storage Domains overview
Yes
Signed-off-by: Brooklyn Dewolf <contact@brooklyn.gent>
=> Added "Allocated Space" column in Storage Domains overview

frontend/webadmin/modules/webadmin/src/main/java/org/ovirt/engine/ui/webadmin/section/main/view/MainStorageView.java
Added ability to sort on following collumns on Storage tab:
* Allocated space
* Confirmed free space
* Total space
[y]
=> core: ability to sort on more space parameters for storage domains

pom.xml
=> core: Remove unused maven property with dozer version

.isort.cfg, ovirt-engine.spec.in, packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-facts/tasks/main.yml, packaging/ansible-runner-service-project/project/roles/ovirt-ova-extract/files/extract_ova.py, packaging/ansible-runner-service-project/project/roles/ovirt-ova-pack/files/pack_ova.py, packaging/ansible-runner-service-project/project/roles/ovirt-ova-query/files/query_ova.py, packaging/ansible-runner-service-project/project/roles/python-ver-detect/tasks/main.yml, packaging/bin/engine-migrate-he.py.in, packaging/bin/vdsm_to_network_name_map.in, packaging/cinderlib/cinderlib-client.py.in, packaging/services/ovirt-websocket-proxy/ovirt-websocket-proxy.py.in, packaging/setup/plugins/ovirt-engine-setup/websocket_proxy/pki.py
* There is no reason to try and keep compability with python 2.
[y]
=> packaging: removal of the python six module

packaging/setup/ovirt_engine_setup/engine_common/database.py
remove last distutils LooseVersion
y
=> packaging: remove last distutils LooseVersion
